<script setup>
import {computed,onMounted,ref} from 'vue';import api from '../../services/api';import AppIcon from '../common/AppIcon.vue';
const props=defineProps({resource:String,id:[Number,String]}),emit=defineEmits(['close']),record=ref(null),loading=ref(true),error=ref('');
const isPurchase=computed(()=>props.resource==='purchases'),isSale=computed(()=>props.resource==='sales'),isPayment=computed(()=>props.resource==='payments');
const title=computed(()=>isPurchase.value?'Purchase order':isSale.value?'Sales invoice':'Payment receipt');
const number=computed(()=>record.value?.purchase_number||record.value?.sale_number||record.value?.payment_number||'');
const party=computed(()=>record.value?.supplier||record.value?.customer||null);
const date=computed(()=>record.value?.purchase_date||record.value?.sale_date||record.value?.payment_date);
const money=v=>'PKR '+Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
function formatDate(v){return v?new Date(v).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'—'}
function printDocument(){window.print()}
onMounted(async()=>{try{record.value=(await api.get(`/${props.resource}/${props.id}`)).data.data}catch(e){error.value=e.response?.data?.message||'Unable to load details.'}finally{loading.value=false}});
</script>
<template><Teleport to="body"><div class="modal-backdrop" @click.self="emit('close')"><section class="detail-modal">
<div class="modal-toolbar no-print"><div><span class="eyebrow">{{title}}</span><strong>{{number}}</strong></div><div><button class="secondary with-icon" @click="printDocument"><AppIcon name="print"/>Print</button><button class="icon-only secondary" title="Close" @click="emit('close')"><AppIcon name="close"/></button></div></div>
<div v-if="loading" class="empty-state">Loading details…</div><div v-else-if="error" class="error">{{error}}</div>
<article v-else class="print-document">
<header class="document-head"><div><div class="document-logo">SM</div><h2>Stock Manager</h2><p>Procurement, sales & inventory</p></div><div class="document-title"><span>{{title}}</span><strong>{{number}}</strong><em class="status" :class="record.status==='cancelled'||record.is_reversed?'neutral':'success'">{{record.status||((record.is_reversed)?'Reversed':'Received')}}</em></div></header>
<div class="document-meta"><div><label>{{isPurchase?'Supplier':isSale?'Bill to':'Received from / paid to'}}</label><strong>{{party?.name||'—'}}</strong><span>{{party?.contact_person||''}}</span><span>{{party?.phone||''}}</span><span>{{party?.email||''}}</span><span>{{party?.address||''}}</span></div><div class="meta-list"><div><span>Date</span><strong>{{formatDate(date)}}</strong></div><div v-if="record.payment_method"><span>Payment method</span><strong>{{String(record.payment_method).replaceAll('_',' ')}}</strong></div><div v-if="record.payment_status"><span>Payment status</span><strong>{{record.payment_status}}</strong></div><div v-if="record.supplier_invoice_number"><span>Supplier invoice</span><strong>{{record.supplier_invoice_number}}</strong></div></div></div>
<div v-if="!isPayment" class="document-table"><table><thead><tr><th>#</th><th>Product</th><th>SKU</th><th class="number">Qty</th><th class="number">Unit price</th><th class="number">Discount</th><th class="number">Total</th></tr></thead><tbody><tr v-for="(item,index) in record.items" :key="item.id"><td>{{index+1}}</td><td><strong>{{item.product?.name}}</strong></td><td>{{item.product?.sku}}</td><td class="number">{{Number(item.quantity).toLocaleString(undefined,{maximumFractionDigits:3})}}</td><td class="number">{{money(item.unit_price)}}</td><td class="number">{{money(item.discount)}}</td><td class="number"><strong>{{money(item.line_total)}}</strong></td></tr></tbody></table></div>
<div v-if="!isPayment" class="document-bottom"><div class="document-notes"><label>Notes</label><p>{{record.notes||'No notes were added to this transaction.'}}</p></div><div class="document-totals"><div><span>Subtotal</span><strong>{{money(record.subtotal)}}</strong></div><div><span>Discount</span><strong>- {{money(record.discount)}}</strong></div><div v-if="isPurchase"><span>Additional cost</span><strong>{{money(record.additional_cost)}}</strong></div><div v-if="isSale"><span>Tax</span><strong>{{money(record.tax)}}</strong></div><div class="grand"><span>Grand total</span><strong>{{money(record.grand_total)}}</strong></div><div><span>Paid</span><strong>{{money(record.paid_amount)}}</strong></div><div><span>Balance due</span><strong>{{money(record.due_amount)}}</strong></div></div></div>
<div v-else class="receipt-body"><div class="receipt-amount"><span>Amount {{record.is_reversed?'reversed':'received'}}</span><strong>{{money(record.amount)}}</strong></div><div class="receipt-grid"><div><span>Payment type</span><strong>{{String(record.payment_type).replaceAll('_',' ')}}</strong></div><div><span>Method</span><strong>{{String(record.payment_method).replaceAll('_',' ')}}</strong></div><div><span>Reference</span><strong>{{record.reference_number||'—'}}</strong></div><div><span>Linked transaction</span><strong>{{record.purchase?.purchase_number||record.sale?.sale_number||'General payment'}}</strong></div></div><div class="document-notes"><label>Notes</label><p>{{record.notes||'No notes were added to this payment.'}}</p></div></div>
<footer class="document-footer"><span>Generated by Stock Manager</span><span>{{new Date().toLocaleString()}}</span></footer>
</article></section></div></Teleport></template>
