<script setup>
import {computed,onBeforeUnmount,onMounted,ref} from 'vue';import api from '../../services/api';import AppIcon from '../common/AppIcon.vue';
const props=defineProps({resource:String,apiResource:{type:String,default:null},id:[Number,String]}),emit=defineEmits(['close']),record=ref(null),loading=ref(true),pdfLoading=ref(false),error=ref('');
const endpoint=computed(()=>props.apiResource||props.resource);
const isPurchase=computed(()=>props.resource==='purchases'),isSale=computed(()=>props.resource==='sales'),isPayment=computed(()=>props.resource==='payments');
const title=computed(()=>isPurchase.value?'Purchase order':isSale.value?'Sales invoice':record.value?.payment_type==='customer_payment'?'Receipt voucher':'Payment voucher');
const voucherAction=computed(()=>record.value?.payment_type==='customer_payment'?'Received':'Paid');
const number=computed(()=>record.value?.purchase_number||record.value?.sale_number||record.value?.payment_number||'');
const party=computed(()=>record.value?.supplier||record.value?.customer||null);
const date=computed(()=>record.value?.purchase_date||record.value?.sale_date||record.value?.payment_date);
const money=v=>'PKR '+Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
function formatDate(v){return v?new Date(v).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'—'}
async function printDocument(){
 const popup=window.open('','_blank');
 pdfLoading.value=true;
 try{
  const response=await api.get(`/${endpoint.value}/${record.value.id}/pdf`,{responseType:'blob'});
  const url=URL.createObjectURL(new Blob([response.data],{type:'application/pdf'}));
  if(popup)popup.location.href=url;else window.location.href=url;
  setTimeout(()=>URL.revokeObjectURL(url),60000);
 }catch(e){if(popup)popup.close();error.value=e.response?.data?.message||'Unable to generate voucher PDF.'}finally{pdfLoading.value=false}
}
function keydown(event){if(event.key==='Escape')emit('close')}
onMounted(async()=>{document.body.style.overflow='hidden';window.addEventListener('keydown',keydown);try{record.value=(await api.get(`/${endpoint.value}/${props.id}`)).data.data}catch(e){error.value=e.response?.data?.message||'Unable to load details.'}finally{loading.value=false}});
onBeforeUnmount(()=>{document.body.style.overflow='';window.removeEventListener('keydown',keydown)});
</script>
<template><Teleport to="body"><div class="modal-backdrop" @click.self="emit('close')"><section class="detail-modal">
<div class="modal-toolbar no-print"><div><span class="eyebrow">{{title}}</span><strong>{{number}}</strong></div><div><button class="secondary with-icon" :disabled="pdfLoading" @click="printDocument"><span v-if="pdfLoading" class="spinner dark"></span><AppIcon v-else name="print"/>{{pdfLoading?'Generating…':'Open PDF'}}</button><button class="icon-only secondary" title="Close" @click="emit('close')"><AppIcon name="close"/></button></div></div>
<div v-if="loading" class="empty-state">Loading details…</div><div v-else-if="error" class="error">{{error}}</div>
<article v-else class="print-document">
<header class="document-head"><div><div class="document-logo">SM</div><h2>Stock Manager</h2><p>Procurement, sales & inventory</p></div><div class="document-title"><span>{{title}}</span><strong>{{number}}</strong><em class="status" :class="record.status==='cancelled'||record.is_reversed?'neutral':'success'">{{record.status||((record.is_reversed)?'Reversed':voucherAction)}}</em></div></header>
<div class="document-meta"><div><label>{{isPurchase?'Supplier':isSale?'Bill to':record.payment_type==='customer_payment'?'Received from':'Paid to'}}</label><strong>{{party?.name||'—'}}</strong><span>{{party?.contact_person||''}}</span><span>{{party?.phone||''}}</span><span>{{party?.email||''}}</span><span>{{party?.address||''}}</span></div><div class="meta-list"><div><span>Date</span><strong>{{formatDate(date)}}</strong></div><div v-if="record.payment_method"><span>Payment method</span><strong>{{String(record.payment_method).replaceAll('_',' ')}}</strong></div><div v-if="record.payment_status"><span>Payment status</span><strong>{{record.payment_status}}</strong></div><div v-if="record.supplier_invoice_number"><span>Supplier invoice</span><strong>{{record.supplier_invoice_number}}</strong></div></div></div>
<div v-if="!isPayment" class="document-table"><table><thead><tr><th>#</th><th>Product</th><th>SKU</th><th class="number">Qty</th><th class="number">Unit price</th><th class="number">Discount</th><th class="number">Total</th></tr></thead><tbody><tr v-for="(item,index) in record.items" :key="item.id"><td>{{index+1}}</td><td><strong>{{item.product?.name}}</strong></td><td>{{item.product?.sku}}</td><td class="number">{{Number(item.quantity).toLocaleString(undefined,{maximumFractionDigits:3})}}</td><td class="number">{{money(item.unit_price)}}</td><td class="number">{{money(item.discount)}}</td><td class="number"><strong>{{money(item.line_total)}}</strong></td></tr></tbody></table></div>
<div v-if="!isPayment" class="document-bottom"><div class="document-notes"><label>Notes</label><p>{{record.notes||'No notes were added to this transaction.'}}</p></div><div class="document-totals"><div><span>Subtotal</span><strong>{{money(record.subtotal)}}</strong></div><div><span>Discount</span><strong>- {{money(record.discount)}}</strong></div><div v-if="isPurchase"><span>Additional cost</span><strong>{{money(record.additional_cost)}}</strong></div><div v-if="isSale"><span>Tax</span><strong>{{money(record.tax)}}</strong></div><div class="grand"><span>Grand total</span><strong>{{money(record.grand_total)}}</strong></div><div><span>Paid</span><strong>{{money(record.paid_amount)}}</strong></div><div><span>Balance due</span><strong>{{money(record.due_amount)}}</strong></div></div></div>
<div v-if="!isPayment" class="payment-history"><div class="history-head"><div><label>Payment history</label><p>Initial and partial installments recorded against this transaction.</p></div><strong>{{record.payments?.length||0}} voucher{{record.payments?.length===1?'':'s'}}</strong></div><table><thead><tr><th>Voucher</th><th>Date</th><th>Method</th><th>Status</th><th class="number">Amount</th></tr></thead><tbody><tr v-for="payment in record.payments" :key="payment.id"><td><strong>{{payment.payment_number}}</strong></td><td>{{formatDate(payment.payment_date)}}</td><td>{{String(payment.payment_method).replaceAll('_',' ')}}</td><td><span class="status" :class="payment.is_reversed?'neutral':'success'">{{payment.is_reversed?'Reversed':'Posted'}}</span></td><td class="number"><strong>{{money(payment.amount)}}</strong></td></tr><tr v-if="!record.payments?.length"><td colspan="5" class="empty-history">No payment vouchers recorded.</td></tr></tbody></table></div>
<div v-else class="receipt-body"><div class="receipt-amount"><span>Amount {{record.is_reversed?'reversed':voucherAction.toLowerCase()}}</span><strong>{{money(record.amount)}}</strong></div><div class="receipt-grid"><div><span>Voucher type</span><strong>{{title}}</strong></div><div><span>Method</span><strong>{{String(record.payment_method).replaceAll('_',' ')}}</strong></div><div><span>Reference</span><strong>{{record.reference_number||'—'}}</strong></div><div><span>Linked transaction</span><strong>{{record.purchase?.purchase_number||record.sale?.sale_number||'General payment'}}</strong></div></div><div class="document-notes"><label>Notes</label><p>{{record.notes||'No notes were added to this voucher.'}}</p></div></div>
<footer class="document-footer"><span>Generated by Stock Manager</span><span>{{new Date().toLocaleString()}}</span></footer>
</article></section></div></Teleport></template>
