<?php
namespace Tests\Feature;
use App\Models\{Customer,Product,Supplier,User};
use Illuminate\Foundation\Testing\RefreshDatabase;
use Laravel\Sanctum\Sanctum;
use Spatie\Permission\Models\{Permission,Role};
use Tests\TestCase;
class InventoryFlowTest extends TestCase {
    use RefreshDatabase;
    private User $user; private Supplier $supplier; private Customer $customer; private Product $product;
    protected function setUp():void{parent::setUp();$this->user=User::factory()->create();$permissions=['dashboard.view','products.view','products.manage','suppliers.view','suppliers.manage','customers.view','customers.manage','purchases.view','purchases.create','purchases.cancel','sales.view','sales.create','sales.cancel','stock.view','stock.adjust','payments.view','payments.create','reports.view','users.manage','settings.manage'];foreach($permissions as $name)Permission::create(['name'=>$name,'guard_name'=>'sanctum']);$role=Role::create(['name'=>'Administrator','guard_name'=>'sanctum']);$role->givePermissionTo($permissions);$this->user->assignRole($role);Sanctum::actingAs($this->user);
        $this->supplier=Supplier::create(['name'=>'Supplier','opening_balance'=>0]);$this->customer=Customer::create(['name'=>'Customer','opening_balance'=>0]);
        $this->product=Product::create(['name'=>'Widget','sku'=>'W-1','unit'=>'piece','purchase_price'=>10,'sale_price'=>20,'average_cost'=>0,'minimum_stock_level'=>2,'current_stock'=>0]);}
    private function purchase(float $qty=10,float $price=10,float $paid=0){return $this->postJson('/api/purchases',['purchase_date'=>'2026-07-25','supplier_id'=>$this->supplier->id,'payment_method'=>'cash','discount'=>0,'additional_cost'=>0,'paid_amount'=>$paid,'items'=>[['product_id'=>$this->product->id,'quantity'=>$qty,'unit_price'=>$price,'discount'=>0]]]);}
    private function sale(float $qty=3,float $price=20,float $paid=0){return $this->postJson('/api/sales',['sale_date'=>'2026-07-25','customer_id'=>$this->customer->id,'payment_method'=>'cash','discount'=>0,'tax'=>0,'paid_amount'=>$paid,'items'=>[['product_id'=>$this->product->id,'quantity'=>$qty,'unit_price'=>$price,'discount'=>0]]]);}
    public function test_product_creation_and_login():void{$this->postJson('/api/products',['name'=>'Other','sku'=>'O-1','unit'=>'box','purchase_price'=>2,'sale_price'=>3,'minimum_stock_level'=>1,'is_active'=>true])->assertCreated();$this->assertDatabaseHas('products',['sku'=>'O-1']);}
    public function test_purchase_increases_stock_and_calculates_weighted_cost():void{$first=$this->purchase(10,10)->assertCreated();$purchaseId=$first->json('data.id');$this->purchase(10,20)->assertCreated();$this->assertEquals(20,(float)$this->product->fresh()->current_stock);$this->assertEquals(15,(float)$this->product->fresh()->average_cost);$this->assertDatabaseCount('stock_movements',2);$this->getJson('/api/purchases/'.$purchaseId)->assertOk()->assertJsonPath('data.items.0.product.sku','W-1');$pdf=$this->get('/api/purchases/'.$purchaseId.'/pdf');$pdf->assertOk()->assertHeader('content-type','application/pdf');$this->assertStringStartsWith('%PDF-',$pdf->getContent());}
    public function test_sale_decreases_stock_and_saves_cost_for_profit():void{$this->purchase()->assertCreated();$sale=$this->sale(3)->assertCreated();$this->assertEquals(7,(float)$this->product->fresh()->current_stock);$this->assertDatabaseHas('sale_items',['quantity'=>3,'unit_cost'=>10]);$pdf=$this->get('/api/sales/'.$sale->json('data.id').'/pdf');$pdf->assertOk()->assertHeader('content-type','application/pdf');$this->assertStringStartsWith('%PDF-',$pdf->getContent());$this->getJson('/api/reports/profit')->assertOk()->assertJsonPath('data.rows.0.gross_profit',30)->assertJsonPath('data.summary.margin_percent',50);}
    public function test_insufficient_stock_rolls_back_sale():void{$this->purchase(2)->assertCreated();$this->sale(3)->assertUnprocessable();$this->assertDatabaseCount('sales',0);$this->assertEquals(2,(float)$this->product->fresh()->current_stock);}
    public function test_purchase_and_sale_cancellations_reverse_stock():void{$purchase=$this->purchase(10)->json('data');$sale=$this->sale(3)->json('data');$this->postJson('/api/sales/'.$sale['id'].'/cancel')->assertOk();$this->assertEquals(10,(float)$this->product->fresh()->current_stock);$this->postJson('/api/purchases/'.$purchase['id'].'/cancel')->assertOk();$this->assertEquals(0,(float)$this->product->fresh()->current_stock);}
    public function test_payments_update_balance_and_overpayment_is_rejected():void{$this->purchase(10,10)->assertCreated();$payment=$this->postJson('/api/payments',['payment_date'=>'2026-07-25','payment_type'=>'supplier_payment','supplier_id'=>$this->supplier->id,'amount'=>40,'payment_method'=>'cash'])->assertCreated();$paymentId=$payment->json('data.id');$this->getJson('/api/payments/'.$paymentId)->assertOk()->assertJsonPath('data.supplier.name','Supplier');$pdf=$this->get('/api/payments/'.$paymentId.'/pdf');$pdf->assertOk()->assertHeader('content-type','application/pdf');$this->assertStringStartsWith('%PDF-', $pdf->getContent());$this->getJson('/api/suppliers/'.$this->supplier->id.'/ledger')->assertJsonPath('data.outstanding',60);$this->postJson('/api/payments',['payment_date'=>'2026-07-25','payment_type'=>'supplier_payment','supplier_id'=>$this->supplier->id,'amount'=>61,'payment_method'=>'cash'])->assertUnprocessable();}
    public function test_partial_payment_history_updates_document_balance():void{$purchase=$this->purchase(10,10)->assertCreated()->json('data');$this->getJson('/api/payments/outstanding?payment_type=supplier_payment&party_id='.$this->supplier->id)->assertOk()->assertJsonPath('data.0.due',100);$this->postJson('/api/payments',['payment_date'=>'2026-07-26','payment_type'=>'supplier_payment','supplier_id'=>$this->supplier->id,'purchase_id'=>$purchase['id'],'amount'=>35,'payment_method'=>'bank_transfer'])->assertCreated();$this->assertDatabaseHas('purchases',['id'=>$purchase['id'],'paid_amount'=>35,'due_amount'=>65,'payment_status'=>'partial']);$this->postJson('/api/payments',['payment_date'=>'2026-07-27','payment_type'=>'supplier_payment','supplier_id'=>$this->supplier->id,'purchase_id'=>$purchase['id'],'amount'=>65,'payment_method'=>'cash'])->assertCreated();$this->getJson('/api/purchases/'.$purchase['id'])->assertOk()->assertJsonPath('data.payment_status','paid')->assertJsonCount(2,'data.payments');}
    public function test_payment_context_shows_party_balance_open_documents_and_running_history():void{$purchase=$this->purchase(10,10)->assertCreated()->json('data');$this->postJson('/api/payments',['payment_date'=>'2026-07-26','payment_type'=>'supplier_payment','supplier_id'=>$this->supplier->id,'purchase_id'=>$purchase['id'],'amount'=>35,'payment_method'=>'bank_transfer'])->assertCreated();$this->getJson('/api/payments/context?payment_type=supplier_payment&party_id='.$this->supplier->id)->assertOk()->assertJsonPath('data.summary.direction','transfer_out')->assertJsonPath('data.summary.billed_total',100)->assertJsonPath('data.summary.settled_total',35)->assertJsonPath('data.summary.outstanding_balance',65)->assertJsonPath('data.outstanding.0.due',65)->assertJsonPath('data.history.0.type','Payment')->assertJsonPath('data.history.0.running_balance',65);}
    public function test_administrator_can_create_user_with_role():void{Role::create(['name'=>'Operator','guard_name'=>'sanctum']);$this->postJson('/api/users',['name'=>'Store Operator','email'=>'operator@example.com','password'=>'secure123','password_confirmation'=>'secure123','role'=>'Operator','is_active'=>true])->assertCreated()->assertJsonPath('data.roles.0.name','Operator');$this->assertDatabaseHas('users',['email'=>'operator@example.com','is_active'=>true]);}
    public function test_administrator_can_update_company_details():void{$this->putJson('/api/company-settings',['company_name'=>'Pro Sale Traders','company_tagline'=>'Wholesale and Retail','company_address'=>'Lahore, Pakistan','company_phone'=>'0300-1234567','company_email'=>'accounts@prosale.test','company_website'=>'prosale.test','company_tax_number'=>'NTN-12345','currency'=>'PKR'])->assertOk()->assertJsonPath('data.company_name','Pro Sale Traders');$this->assertDatabaseHas('settings',['key'=>'company_phone','value'=>'0300-1234567']);}
    public function test_document_numbers_include_type_month_letter_year_and_sequence():void{$purchase=$this->purchase(10,10,25)->assertCreated()->assertJsonPath('data.purchase_number','PO_G26-001')->assertJsonPath('data.payments.0.payment_number','PV_G26-001');$this->sale(2,20,10)->assertCreated()->assertJsonPath('data.sale_number','SI_G26-001')->assertJsonPath('data.payments.0.payment_number','RV_G26-001');$this->purchase(1,10)->assertCreated()->assertJsonPath('data.purchase_number','PO_G26-002');}
    public function test_financial_report_reconciles_channels_receivables_and_payables():void{$this->purchase(10,10,25)->assertCreated();$this->sale(2,20,10)->assertCreated();$this->getJson('/api/reports/financial?date_from=2026-07-01&date_to=2026-07-31')->assertOk()->assertJsonPath('data.summary.total_received',10)->assertJsonPath('data.summary.total_paid',25)->assertJsonPath('data.summary.net_cash_flow',-15)->assertJsonPath('data.summary.customer_receivables',30)->assertJsonPath('data.summary.supplier_payables',75)->assertJsonPath('data.rows.0.payment_method','Cash')->assertJsonPath('data.rows.0.net_movement',-15);}
    public function test_product_stock_ledger_reports_every_in_and_out_movement():void{$this->purchase(10)->assertCreated();$this->sale(3)->assertCreated();$this->getJson('/api/reports/stock-ledger?product_id='.$this->product->id.'&date_from=2026-07-01&date_to=2026-07-31')->assertOk()->assertJsonPath('data.summary.opening_stock',0)->assertJsonPath('data.summary.total_in',10)->assertJsonPath('data.summary.total_out',3)->assertJsonPath('data.summary.closing_stock',7)->assertJsonPath('data.summary.chronology_issues',0)->assertJsonCount(2,'data.rows')->assertJsonPath('data.rows.0.stock_before',0)->assertJsonPath('data.rows.0.stock_after',10)->assertJsonPath('data.rows.1.stock_before',10)->assertJsonPath('data.rows.1.stock_after',7)->assertJsonPath('data.rows.0.source_document','PO_G26-001')->assertJsonPath('data.rows.1.source_document','SI_G26-001');}
}
