<script setup>
import {onMounted,ref} from 'vue';import api from '../services/api';import AppIcon from '../components/common/AppIcon.vue';
const rows=ref([]),form=ref({name:'',code:'',is_active:true}),editing=ref(null),show=ref(false),error=ref(''),notice=ref('');
async function load(){rows.value=(await api.get('/companies')).data.data}
function create(){editing.value=null;form.value={name:'',code:'',is_active:true};show.value=true}
function edit(row){editing.value=row.id;form.value={name:row.name,code:row.code,is_active:row.is_active};show.value=true}
async function save(){error.value='';try{editing.value?await api.put('/companies/'+editing.value,form.value):await api.post('/companies',form.value);show.value=false;notice.value='Company saved successfully.';await load()}catch(e){error.value=Object.values(e.response?.data?.errors||{}).flat().join(' ')||e.response?.data?.message||'Unable to save company.'}}
onMounted(load);
</script>
<template><div class="page-head"><div><span class="eyebrow">Group administration</span><h1>Companies</h1><p class="page-subtitle">Manage operational companies inside the main group.</p></div><button class="with-icon" @click="create"><AppIcon name="plus"/>Add company</button></div><div v-if="notice" class="success-message">{{notice}}</div><form v-if="show" class="panel record-form" @submit.prevent="save"><div class="panel-head"><div><h2>{{editing?'Edit':'Create'}} company</h2><p>Each company receives completely isolated operational data.</p></div></div><div v-if="error" class="error">{{error}}</div><div class="form-grid"><div class="field"><label>Company name</label><input v-model.trim="form.name" required></div><div class="field"><label>Company code</label><input v-model.trim="form.code" required placeholder="e.g. MAIN"></div><label class="switch-row"><div><strong>Active company</strong><span>Inactive companies cannot be selected.</span></div><input v-model="form.is_active" type="checkbox"><i></i></label></div><div class="form-actions"><button>Save company</button><button type="button" class="secondary" @click="show=false">Cancel</button></div></form><section class="panel list-panel"><table><thead><tr><th>S. No.</th><th>Company</th><th>Code</th><th>Status</th><th>Action</th></tr></thead><tbody><tr v-for="(row,index) in rows" :key="row.id"><td>{{index+1}}</td><td><strong>{{row.name}}</strong></td><td>{{row.code}}</td><td><span class="status" :class="row.is_active?'success':'neutral'">{{row.is_active?'Active':'Inactive'}}</span></td><td><button class="icon-only secondary" @click="edit(row)"><AppIcon name="edit"/></button></td></tr></tbody></table></section></template>
