<script setup>
import {computed,onMounted,ref} from 'vue';import api from '../services/api';const d=ref({activity:[]}),loading=ref(true);
onMounted(async()=>{try{d.value=(await api.get('/dashboard')).data.data}finally{loading.value=false}});
const money=v=>'PKR '+Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const maxActivity=computed(()=>Math.max(1,...(d.value.activity||[]).flatMap(x=>[x.sales,x.purchases])));
const metrics=computed(()=>[
 ['Products',d.value.total_products||0,'Active catalogue','blue'],['Stock value',money(d.value.stock_value),'At average cost','violet'],
 ['Sales this month',money(d.value.sales_month),'Revenue recorded','green'],['Gross profit',money(d.value.gross_profit_month),'Current month','amber'],
]);
</script>
<template><div class="page-head"><div><span class="eyebrow">Business overview</span><h1>Good {{new Date().getHours()<12?'morning':new Date().getHours()<17?'afternoon':'evening'}}</h1><p class="page-subtitle">Here is what is happening across sales, purchasing, and inventory.</p></div><div class="date-pill">{{new Date().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}}</div></div>
<div v-if="loading" class="panel empty-state">Loading dashboard…</div><template v-else>
<div class="metric-grid"><div class="metric-card" v-for="[label,value,note,tone] in metrics" :key="label"><div class="metric-top"><span>{{label}}</span><i :class="tone"></i></div><div class="metric-value">{{value}}</div><div class="metric-note">{{note}}</div></div></div>
<div class="dashboard-grid"><section class="panel activity-panel"><div class="panel-head"><div><h2>7-day activity</h2><p>Sales and purchasing volume</p></div><div class="chart-legend"><span><i class="sales"></i>Sales</span><span><i class="purchases"></i>Purchases</span></div></div><div class="bar-chart"><div class="bar-group" v-for="day in d.activity" :key="day.date"><div class="bars"><i class="purchase-bar" :style="{height:`${Math.max(3,day.purchases/maxActivity*130)}px`}"></i><i class="sales-bar" :style="{height:`${Math.max(3,day.sales/maxActivity*130)}px`}"></i></div><span>{{day.date}}</span></div></div></section>
<section class="panel attention-panel"><div class="panel-head"><div><h2>Needs attention</h2><p>Balances and stock warnings</p></div></div><div class="attention-row"><div><span>Customer receivables</span><strong>{{money(d.customer_due)}}</strong></div><span class="status warning">Outstanding</span></div><div class="attention-row"><div><span>Supplier payables</span><strong>{{money(d.supplier_due)}}</strong></div><span class="status neutral">Open</span></div><div class="attention-row"><div><span>Low-stock products</span><strong>{{d.low_stock?.length||0}} products</strong></div><RouterLink to="/reports" class="text-link">Review →</RouterLink></div></section></div>
<div class="dashboard-grid lower"><section class="panel table-panel"><div class="panel-head"><div><h2>Recent sales</h2><p>Latest customer transactions</p></div><RouterLink to="/sales" class="text-link">View all →</RouterLink></div><div class="table-wrap"><table><thead><tr><th>Sale</th><th>Customer</th><th>Status</th><th class="number">Total</th></tr></thead><tbody><tr v-for="s in d.recent_sales" :key="s.id"><td><strong>{{s.sale_number}}</strong><small>{{s.sale_date}}</small></td><td>{{s.customer?.name}}</td><td><span class="status success">{{s.payment_status}}</span></td><td class="number">{{money(s.grand_total)}}</td></tr></tbody></table></div></section>
<section class="panel table-panel"><div class="panel-head"><div><h2>Low stock</h2><p>Products at or below their minimum</p></div><RouterLink to="/reports" class="text-link">Stock report →</RouterLink></div><div class="stock-list"><div v-for="p in d.low_stock" :key="p.id"><div class="product-avatar">{{p.name.slice(0,2).toUpperCase()}}</div><div><strong>{{p.name}}</strong><span>{{p.sku}}</span></div><div class="stock-qty"><strong>{{Number(p.current_stock).toLocaleString()}}</strong><span>{{p.unit}}</span></div></div><div v-if="!d.low_stock?.length" class="empty-state">All products are above minimum stock.</div></div></section></div></template>
</template>
