<script setup>
import {computed,onMounted,ref,watch} from 'vue';
import api from '../services/api';
import AppIcon from '../components/common/AppIcon.vue';
import {can} from '../services/auth';

const today=new Date().toISOString().slice(0,10);
const rows=ref([]),categories=ref([]),loading=ref(false),saving=ref(false),showForm=ref(false),showCategories=ref(false),detail=ref(null),detailLoading=ref(false),pdfLoading=ref(false),error=ref(''),notice=ref(''),page=ref(1),timer=ref();
const pagination=ref({current_page:1,last_page:1,total:0,from:0,to:0,per_page:20});
const summary=ref({filtered_total:0,posted_count:0,cancelled_count:0,today_total:0,month_total:0});
const filters=ref({search:'',expense_category_id:'',payment_method:'',status:'',date_from:'',date_to:''});
const form=ref({expense_date:today,expense_category_id:'',payee_name:'',amount:'',payment_method:'cash',reference_number:'',notes:''});
const categoryForm=ref({id:null,name:'',description:'',is_active:true}),categorySaving=ref(false);
const activeCategories=computed(()=>categories.value.filter(category=>category.is_active));

const money=value=>'PKR '+Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const formatDate=value=>value?new Date(value).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'—';
const method=value=>String(value||'').replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase());

async function load(){loading.value=true;error.value='';try{const {data}=await api.get('/expenses',{params:{...filters.value,page:page.value}});const result=data.data.records;rows.value=result.data.map((row,index)=>({...row,serial:(result.current_page-1)*result.per_page+index+1}));pagination.value={current_page:result.current_page,last_page:result.last_page,total:result.total,from:result.from||0,to:result.to||0,per_page:result.per_page};summary.value=data.data.summary}catch(e){error.value=e.response?.data?.message||'Unable to load expenses.'}finally{loading.value=false}}
async function loadCategories(){try{categories.value=(await api.get('/expenses/categories')).data.data}catch(e){error.value=e.response?.data?.message||'Unable to load expense categories.'}}
function create(){form.value={expense_date:today,expense_category_id:activeCategories.value[0]?.id||'',payee_name:'',amount:'',payment_method:'cash',reference_number:'',notes:''};showForm.value=true;error.value=''}
async function save(){saving.value=true;error.value='';notice.value='';try{const {data}=await api.post('/expenses',form.value);showForm.value=false;notice.value=`Expense ${data.data.expense_number} created with payment voucher ${data.data.payment.payment_number}.`;await load();setTimeout(()=>notice.value='',5000)}catch(e){error.value=Object.values(e.response?.data?.errors||{}).flat().join(' ')||e.response?.data?.message||'Unable to create expense.'}finally{saving.value=false}}
async function openDetail(row){detailLoading.value=true;detail.value={...row};try{detail.value=(await api.get('/expenses/'+row.id)).data.data}catch(e){error.value=e.response?.data?.message||'Unable to load expense details.';detail.value=null}finally{detailLoading.value=false}}
async function printExpense(expense=detail.value){if(!expense)return;const popup=window.open('','_blank');pdfLoading.value=true;try{const response=await api.get(`/expenses/${expense.id}/pdf`,{responseType:'blob'});const url=URL.createObjectURL(new Blob([response.data],{type:'application/pdf'}));if(popup)popup.location.href=url;else window.location.href=url;setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){if(popup)popup.close();error.value=e.response?.data?.message||'Unable to generate payment voucher PDF.'}finally{pdfLoading.value=false}}
async function cancelExpense(expense){if(!confirm(`Cancel ${expense.expense_number} and reverse ${expense.payment?.payment_number||'its payment voucher'}?`))return;error.value='';try{const {data}=await api.post(`/expenses/${expense.id}/cancel`);notice.value=data.message;detail.value=null;await load()}catch(e){error.value=Object.values(e.response?.data?.errors||{}).flat().join(' ')||e.response?.data?.message||'Unable to cancel expense.'}}
function editCategory(category){categoryForm.value={id:category.id,name:category.name,description:category.description||'',is_active:category.is_active}}
function resetCategory(){categoryForm.value={id:null,name:'',description:'',is_active:true}}
async function saveCategory(){categorySaving.value=true;error.value='';try{categoryForm.value.id?await api.put('/expense-categories/'+categoryForm.value.id,categoryForm.value):await api.post('/expense-categories',categoryForm.value);notice.value='Expense category saved.';resetCategory();await loadCategories()}catch(e){error.value=Object.values(e.response?.data?.errors||{}).flat().join(' ')||e.response?.data?.message||'Unable to save expense category.'}finally{categorySaving.value=false}}
async function removeCategory(category){if(!confirm(`Delete expense category “${category.name}”?`))return;try{await api.delete('/expense-categories/'+category.id);notice.value='Expense category deleted.';await loadCategories()}catch(e){error.value=Object.values(e.response?.data?.errors||{}).flat().join(' ')||e.response?.data?.message||'Unable to delete expense category.'}}
function resetFilters(){filters.value={search:'',expense_category_id:'',payment_method:'',status:'',date_from:'',date_to:''};page.value=1;load()}
function go(target){if(target<1||target>pagination.value.last_page||target===page.value)return;page.value=target;load()}
watch(()=>filters.value.search,()=>{clearTimeout(timer.value);page.value=1;timer.value=setTimeout(load,300)});
onMounted(()=>{loadCategories();load()});
</script>

<template>
<div class="page-head"><div><span class="eyebrow">Money out</span><h1>Expenses</h1><p class="page-subtitle">Record operating costs and create their payment vouchers automatically.</p></div><div class="page-actions"><button v-if="can('expenses.manage')" class="secondary with-icon" @click="showCategories=!showCategories"><AppIcon name="settings"/>Expense categories</button><button v-if="can('expenses.create')" class="with-icon" @click="create"><AppIcon name="plus"/>New expense</button></div></div>
<div v-if="notice" class="success-message">{{notice}}</div><div v-if="error&&!showForm" class="error">{{error}}</div>

<div class="report-summary expense-summary"><div class="summary-card"><span>Expenses today</span><strong>{{money(summary.today_total)}}</strong></div><div class="summary-card"><span>This month</span><strong>{{money(summary.month_total)}}</strong></div><div class="summary-card"><span>Filtered total</span><strong>{{money(summary.filtered_total)}}</strong></div><div class="summary-card"><span>Posted records</span><strong>{{summary.posted_count||0}}</strong></div><div class="summary-card"><span>Cancelled records</span><strong>{{summary.cancelled_count||0}}</strong></div></div>

<section v-if="showCategories&&can('expenses.manage')" class="panel expense-category-panel"><div class="panel-head"><div><h2>Expense categories</h2><p>Categories are isolated to the selected company.</p></div><button class="icon-only secondary" @click="showCategories=false"><AppIcon name="close"/></button></div><div class="expense-category-grid"><form @submit.prevent="saveCategory"><div class="field"><label>Category name</label><input v-model.trim="categoryForm.name" required placeholder="e.g. Utilities"></div><div class="field"><label>Description <span>Optional</span></label><input v-model.trim="categoryForm.description" placeholder="What belongs in this category?"></div><label class="switch-row"><div><strong>Active category</strong><span>Inactive categories remain on old expenses.</span></div><input v-model="categoryForm.is_active" type="checkbox"><i></i></label><div class="form-actions"><button :disabled="categorySaving">{{categorySaving?'Saving…':categoryForm.id?'Update category':'Add category'}}</button><button v-if="categoryForm.id" type="button" class="secondary" @click="resetCategory">Cancel edit</button></div></form><div class="expense-category-list"><div v-for="category in categories" :key="category.id"><div><strong>{{category.name}}</strong><span>{{category.description||'No description'}} · {{category.expenses_count}} expense{{category.expenses_count===1?'':'s'}}</span></div><span class="status" :class="category.is_active?'success':'neutral'">{{category.is_active?'Active':'Inactive'}}</span><div class="row-actions"><button class="icon-only secondary" title="Edit category" @click="editCategory(category)"><AppIcon name="edit"/></button><button class="icon-only secondary danger-button" title="Delete category" @click="removeCategory(category)"><AppIcon name="close"/></button></div></div></div></div></section>

<form v-if="showForm" class="panel record-form expense-form" @submit.prevent="save"><div class="panel-head"><div><h2>Create expense</h2><p>Saving posts the expense and generates a Payment Voucher immediately.</p></div><button type="button" class="icon-only secondary" @click="showForm=false"><AppIcon name="close"/></button></div><div v-if="error" class="error">{{error}}</div><div class="form-grid"><div class="field"><label>Expense date</label><input v-model="form.expense_date" type="date" required></div><div class="field"><label>Category</label><select v-model="form.expense_category_id" required><option value="" disabled>Select category…</option><option v-for="category in activeCategories" :key="category.id" :value="category.id">{{category.name}}</option></select></div><div class="field"><label>Paid to</label><input v-model.trim="form.payee_name" required placeholder="Person or business name"></div><div class="field"><label>Amount</label><input v-model="form.amount" type="number" min="0.01" step="0.01" required placeholder="0.00"></div><div class="field"><label>Payment method</label><select v-model="form.payment_method"><option value="cash">Cash out</option><option value="bank_transfer">Bank transfer out</option><option value="card">Card</option><option value="other">Other</option></select></div><div class="field"><label>Reference number <span>Optional</span></label><input v-model.trim="form.reference_number" placeholder="Cheque, bill, or transfer reference"></div><div class="field expense-notes"><label>Narration / notes <span>Optional</span></label><textarea v-model.trim="form.notes" rows="3" placeholder="Purpose and supporting details…"></textarea></div></div><div class="expense-posting-note"><AppIcon name="payment-out"/><div><strong>A payment voucher will be posted</strong><span>The expense and voucher are saved together. Cancel the expense to reverse the voucher.</span></div></div><div class="form-actions"><button class="with-icon" :disabled="saving"><AppIcon name="plus"/>{{saving?'Posting expense…':'Post expense & create PV'}}</button><button type="button" class="secondary" @click="showForm=false">Cancel</button></div></form>

<section class="panel filter-panel"><div class="filter-grid expense-filters"><div class="field"><label>Search</label><input v-model="filters.search" placeholder="Expense, payee, reference…"></div><div class="field"><label>Category</label><select v-model="filters.expense_category_id"><option value="">All categories</option><option v-for="category in categories" :key="category.id" :value="category.id">{{category.name}}</option></select></div><div class="field"><label>Payment method</label><select v-model="filters.payment_method"><option value="">All methods</option><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="other">Other</option></select></div><div class="field"><label>Status</label><select v-model="filters.status"><option value="">All statuses</option><option value="posted">Posted</option><option value="cancelled">Cancelled</option></select></div><div class="field"><label>From</label><input v-model="filters.date_from" type="date"></div><div class="field"><label>To</label><input v-model="filters.date_to" type="date"></div><div class="filter-actions"><button class="with-icon" @click="page=1;load()"><AppIcon name="search"/>Apply</button><button class="secondary" @click="resetFilters">Reset</button></div></div></section>

<section class="panel list-panel"><div v-if="loading" class="table-loading">Loading expenses…</div><div class="table-wrap"><table><thead><tr><th>S. No.</th><th>Expense</th><th>Date</th><th>Category</th><th>Paid to</th><th>Method / reference</th><th>Payment voucher</th><th class="number">Amount</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td>{{row.serial}}</td><td><strong>{{row.expense_number}}</strong></td><td>{{formatDate(row.expense_date)}}</td><td>{{row.category?.name||'—'}}</td><td><strong>{{row.payee_name}}</strong></td><td>{{method(row.payment_method)}}<small>{{row.reference_number||'No reference'}}</small></td><td><strong>{{row.payment?.payment_number||'—'}}</strong></td><td class="number"><strong>{{money(row.amount)}}</strong></td><td><span class="status" :class="row.status==='posted'?'success':'neutral'">{{row.status}}</span></td><td><div class="row-actions"><button class="icon-only secondary" title="View expense" @click="openDetail(row)"><AppIcon name="eye"/></button><button class="icon-only secondary" title="Open payment voucher PDF" @click="printExpense(row)"><AppIcon name="print"/></button><button v-if="row.status==='posted'&&can('expenses.cancel')" class="icon-only secondary danger-button" title="Cancel expense" @click="cancelExpense(row)"><AppIcon name="close"/></button></div></td></tr><tr v-if="!loading&&!rows.length"><td colspan="10"><div class="empty-state"><strong>No expenses found</strong><span>Create an expense or change the filters.</span></div></td></tr></tbody></table></div><div class="pagination" v-if="pagination.last_page>1"><span>Showing {{pagination.from}}–{{pagination.to}} of {{pagination.total}}</span><div><button class="secondary" :disabled="page===1" @click="go(page-1)">Previous</button><span>Page {{page}} of {{pagination.last_page}}</span><button class="secondary" :disabled="page===pagination.last_page" @click="go(page+1)">Next</button></div></div></section>

<Teleport to="body"><div v-if="detail" class="modal-backdrop" @click.self="detail=null"><section class="detail-modal expense-detail"><div class="modal-toolbar"><div><span class="eyebrow">Expense record</span><strong>{{detail.expense_number}}</strong></div><div><button class="secondary with-icon" :disabled="pdfLoading" @click="printExpense(detail)"><AppIcon name="print"/>{{pdfLoading?'Generating…':'Open PV PDF'}}</button><button class="icon-only secondary" @click="detail=null"><AppIcon name="close"/></button></div></div><article class="print-document"><header class="document-head"><div><div class="document-logo"><AppIcon name="expense" :size="22"/></div><h2>{{detail.category?.name}}</h2><p>Operating expense</p></div><div class="document-title"><span>Expense</span><strong>{{detail.expense_number}}</strong><em class="status" :class="detail.status==='posted'?'success':'neutral'">{{detail.status}}</em></div></header><div class="receipt-body"><div class="receipt-amount"><span>Amount paid</span><strong>{{money(detail.amount)}}</strong></div><div class="receipt-grid"><div><span>Paid to</span><strong>{{detail.payee_name}}</strong></div><div><span>Expense date</span><strong>{{formatDate(detail.expense_date)}}</strong></div><div><span>Payment method</span><strong>{{method(detail.payment_method)}}</strong></div><div><span>Payment voucher</span><strong>{{detail.payment?.payment_number||'—'}}</strong></div><div><span>Reference</span><strong>{{detail.reference_number||'—'}}</strong></div><div><span>Recorded by</span><strong>{{detail.creator?.name||'—'}}</strong></div></div><div class="document-notes"><label>Narration / notes</label><p>{{detail.notes||'No notes were added to this expense.'}}</p></div></div></article></section></div></Teleport>
</template>
