<script setup>
import {computed,onMounted,ref,watch} from 'vue';import api from '../services/api';
const props=defineProps({resource:String}),rows=ref([]),search=ref(''),loading=ref(false),timer=ref(),columns=ref([]),showForm=ref(false),editing=ref(null),error=ref(''),options=ref({suppliers:[],customers:[],products:[]});
const configs={products:[['name','Name','text'],['sku','SKU','text'],['barcode','Barcode','text'],['unit','Unit','text'],['purchase_price','Purchase price','number'],['sale_price','Sale price','number'],['minimum_stock_level','Minimum stock','number'],['opening_stock','Opening stock','number']],
suppliers:[['name','Supplier name','text'],['contact_person','Contact person','text'],['phone','Phone','text'],['email','Email','email'],['opening_balance','Opening balance','number']],
customers:[['name','Customer name','text'],['phone','Phone','text'],['email','Email','email'],['opening_balance','Opening balance','number']],
payments:[['payment_date','Payment date','date'],['payment_type','Payment type','payment_type'],['supplier_id','Supplier','supplier'],['customer_id','Customer','customer'],['amount','Amount','number'],['payment_method','Payment method','payment_method']],
'stock-movements':[['adjustment_date','Date','date'],['product_id','Product','product'],['adjustment_type','Adjustment type','adjustment_type'],['quantity','Quantity','number'],['reason','Reason','text']]};
const canForm=computed(()=>!!configs[props.resource]),form=ref({});
function defaults(){form.value={is_active:true,unit:'piece',purchase_price:0,sale_price:0,minimum_stock_level:0,opening_stock:0,opening_balance:0,payment_date:new Date().toISOString().slice(0,10),adjustment_date:new Date().toISOString().slice(0,10),payment_method:'cash',payment_type:'supplier_payment',adjustment_type:'increase'}}
async function load(){loading.value=true;try{const r=(await api.get('/'+props.resource,{params:{search:search.value}})).data.data;rows.value=r.data||r;columns.value=rows.value.length?Object.keys(rows.value[0]).filter(k=>!['deleted_at','updated_at','description','notes'].includes(k)&&typeof rows.value[0][k]!=='object').slice(0,7):[]}finally{loading.value=false}}
async function loadOptions(){for(const x of ['suppliers','customers','products']){try{options.value[x]=(await api.get('/'+x,{params:{per_page:100,active:1}})).data.data.data}catch{}}}
function create(){editing.value=null;defaults();showForm.value=true}function edit(row){editing.value=row.id;form.value={...row};showForm.value=true}
async function save(){error.value='';try{let endpoint='/'+props.resource;if(props.resource==='stock-movements')endpoint='/stock-adjustments';if(editing.value)await api.put(endpoint+'/'+editing.value,form.value);else await api.post(endpoint,form.value);showForm.value=false;await load()}catch(e){error.value=Object.values(e.response?.data?.errors||{}).flat().join(' ')||e.response?.data?.message||'Unable to save.'}}
watch(()=>props.resource,()=>{showForm.value=false;load();loadOptions()});watch(search,()=>{clearTimeout(timer.value);timer.value=setTimeout(load,300)});onMounted(()=>{defaults();load();loadOptions()});
</script>
<template><div class="page-head"><h1>{{resource.replace('-',' ').replace(/\b\w/g,c=>c.toUpperCase())}}</h1><div style="display:flex;gap:8px"><RouterLink v-if="resource==='purchases'||resource==='sales'" class="btn" :to="`/${resource}/new`">New {{resource.slice(0,-1)}}</RouterLink><button v-if="canForm" @click="create">{{resource==='stock-movements'?'New adjustment':'New record'}}</button></div></div>
<form v-if="showForm" class="panel" style="margin-bottom:16px" @submit.prevent="save"><h2>{{editing?'Edit':'Create'}} record</h2><div v-if="error" class="error">{{error}}</div><div class="form-grid"><div class="field" v-for="[key,label,type] in configs[resource]" v-show="!((key==='supplier_id'&&form.payment_type!=='supplier_payment')||(key==='customer_id'&&form.payment_type!=='customer_payment'))"><label>{{label}}</label>
<select v-if="type==='supplier'||type==='customer'||type==='product'" v-model="form[key]" :required="type==='product'||(type==='supplier'&&form.payment_type==='supplier_payment')||(type==='customer'&&form.payment_type==='customer_payment')"><option value="">Select…</option><option v-for="o in options[type+'s']" :value="o.id">{{o.name}}</option></select>
<select v-else-if="type==='payment_type'" v-model="form[key]"><option value="supplier_payment">Supplier payment</option><option value="customer_payment">Customer payment</option></select>
<select v-else-if="type==='payment_method'" v-model="form[key]"><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="other">Other</option></select>
<select v-else-if="type==='adjustment_type'" v-model="form[key]"><option value="increase">Increase stock</option><option value="decrease">Decrease stock</option></select>
<input v-else v-model="form[key]" :type="type" :step="type==='number'?'.001':undefined" required></div></div><div style="display:flex;gap:8px;margin-top:14px"><button>Save</button><button type="button" class="secondary" @click="showForm=false">Cancel</button></div></form>
<div class="toolbar"><input v-model="search" placeholder="Search…"></div><div class="panel" style="padding:0;overflow:auto"><table><thead><tr><th v-for="c in columns">{{c.replaceAll('_',' ')}}</th><th v-if="['products','suppliers','customers'].includes(resource)">Actions</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td v-for="c in columns">{{r[c]}}</td><td v-if="['products','suppliers','customers'].includes(resource)"><button class="secondary" @click="edit(r)">Edit</button></td></tr><tr v-if="!loading&&!rows.length"><td>No records found.</td></tr></tbody></table></div></template>
