<script setup>
import {computed,onMounted,ref,watch} from 'vue';
import api from '../services/api';
import AppIcon from '../components/common/AppIcon.vue';
import SearchSelect from '../components/common/SearchSelect.vue';
import TransactionDetailModal from '../components/transactions/TransactionDetailModal.vue';
import {can} from '../services/auth';

const props=defineProps({resource:String,paymentType:{type:String,default:null}});
const rows=ref([]),search=ref(''),loading=ref(false),timer=ref(),columns=ref([]),showForm=ref(false),editing=ref(null),detailId=ref(null),error=ref(''),notice=ref(''),page=ref(1);
const pagination=ref({current_page:1,last_page:1,total:0,from:0,to:0,per_page:15});
const options=ref({suppliers:[],customers:[],products:[],categories:[],units:[]}),outstanding=ref([]),paymentContext=ref(null),contextLoading=ref(false);
const configs={
 products:[['name','Name','text'],['sku','SKU','text'],['barcode','Barcode','text'],['product_category_id','Category','category'],['product_subcategory_id','Subcategory','subcategory'],['unit_of_measurement_id','Unit of measurement','uom'],['purchase_price','Purchase price','number'],['sale_price','Sale price','number'],['minimum_stock_level','Minimum stock','number'],['opening_stock','Opening stock','number']],
 suppliers:[['name','Supplier name','text'],['contact_person','Contact person','text'],['phone','Phone','text'],['email','Email','email'],['opening_balance','Opening balance','number']],
 customers:[['name','Customer name','text'],['phone','Phone','text'],['email','Email','email'],['opening_balance','Opening balance','number']],
 payments:[['payment_date','Voucher date','date'],['payment_type','Voucher direction','payment_type'],['supplier_id','Pay to supplier','supplier'],['customer_id','Receive from customer','customer'],['document_id','Apply to transaction','document'],['amount','Amount','number'],['payment_method','Payment method','payment_method'],['reference_number','Reference number','text']],
 'stock-movements':[['adjustment_date','Date','date'],['product_id','Product','product'],['adjustment_type','Adjustment type','adjustment_type'],['quantity','Quantity','number'],['reason','Reason','text']]
};
const preferred={
 products:['serial','name','sku','category_name','subcategory_name','unit','current_stock','sale_price','is_active'],
 suppliers:['serial','name','contact_person','phone','email','opening_balance','is_active'],
 customers:['serial','name','phone','email','opening_balance','is_walk_in','is_active'],
 purchases:['serial','purchase_number','purchase_date','supplier_name','grand_total','paid_amount','due_amount','payment_status','status'],
 sales:['serial','sale_number','sale_date','customer_name','grand_total','paid_amount','due_amount','payment_status','status'],
 payments:['serial','payment_number','payment_date','party_name','amount','payment_method','is_reversed'],
 'stock-movements':['serial','movement_date','product_name','product_sku','movement_type','reference_number','quantity_in','quantity_out','stock_after']
};
const createPermissions={products:'products.manage',suppliers:'suppliers.manage',customers:'customers.manage',payments:'payments.create','stock-movements':'stock.adjust'};
const canForm=computed(()=>!!configs[props.resource]&&can(createPermissions[props.resource])),canEdit=computed(()=>can(createPermissions[props.resource])),canTransactionCreate=computed(()=>can(props.resource==='purchases'?'purchases.create':'sales.create')),detailResource=computed(()=>['purchases','sales','payments'].includes(props.resource)),form=ref({});
const voucherEndpoint=computed(()=>props.paymentType==='customer_payment'?'receipt-vouchers':props.paymentType==='supplier_payment'?'payment-vouchers':'payments');
const pageTitle=computed(()=>props.paymentType==='supplier_payment'?'Payment vouchers':props.paymentType==='customer_payment'?'Receipt vouchers':props.resource.replace('-',' ').replace(/\b\w/g,c=>c.toUpperCase()));
const pageDescription=computed(()=>props.paymentType==='supplier_payment'?'Record and print money paid to suppliers.':props.paymentType==='customer_payment'?'Record and print money received from customers.':`Search, review, and manage ${props.resource.replace('-',' ')}.`);
function defaults(){form.value={is_active:true,unit:'piece',purchase_price:0,sale_price:0,minimum_stock_level:0,opening_stock:0,opening_balance:0,payment_date:new Date().toISOString().slice(0,10),adjustment_date:new Date().toISOString().slice(0,10),payment_method:'cash',payment_type:props.paymentType||'supplier_payment',adjustment_type:'increase',document_id:''};outstanding.value=[];paymentContext.value=null}
function heading(column){return column==='serial'?'S. No.':column.replaceAll('_',' ')}
function value(row,column){
 const raw=row[column];if(['is_active','is_walk_in'].includes(column))return raw?'Yes':'No';if(raw===null||raw===undefined||raw==='')return '—';
 if(['grand_total','paid_amount','due_amount','amount','sale_price','opening_balance'].includes(column))return 'PKR '+Number(raw).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
 if(['current_stock','quantity_in','quantity_out','stock_after'].includes(column))return Number(raw).toLocaleString(undefined,{maximumFractionDigits:3});
 if(column.includes('date'))return new Date(raw).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'});
 if(['payment_method','payment_type','movement_type'].includes(column))return String(raw).replaceAll('_',' ');
 return raw;
}
async function load(){loading.value=true;error.value='';try{const endpoint=props.resource==='payments'?voucherEndpoint.value:props.resource;const result=(await api.get('/'+endpoint,{params:{search:search.value,page:page.value}})).data.data;const list=result.data||result;pagination.value=result.data?{current_page:result.current_page,last_page:result.last_page,total:result.total,from:result.from||0,to:result.to||0,per_page:result.per_page}: {current_page:1,last_page:1,total:list.length,from:list.length?1:0,to:list.length,per_page:list.length||15};rows.value=list.map((x,index)=>({...x,serial:(pagination.value.current_page-1)*pagination.value.per_page+index+1,supplier_name:x.supplier?.name,customer_name:x.customer?.name,party_name:x.supplier?.name||x.customer?.name,product_name:x.product?.name,product_sku:x.product?.sku}));columns.value=preferred[props.resource]||(rows.value.length?Object.keys(rows.value[0]).filter(k=>!['id','product_id','supplier_id','customer_id','purchase_id','sale_id','created_by','deleted_at','updated_at','description','notes'].includes(k)&&!k.endsWith('_id')&&typeof rows.value[0][k]!=='object').slice(0,8):[])}catch(e){error.value=e.response?.data?.message||'Unable to load records.'}finally{loading.value=false}}
async function loadOptions(){for(const x of ['suppliers','customers','products'])try{options.value[x]=(await api.get('/'+x,{params:{per_page:100,active:1}})).data.data.data}catch{}if(can('settings.manage')||can('products.manage'))try{const [categories,units]=await Promise.all([api.get('/product-categories'),api.get('/units-of-measurement')]);options.value.categories=categories.data.data;options.value.units=units.data.data}catch{}}
function searchOptions(type){let list=[];if(['supplier','customer','product'].includes(type))list=options.value[type+'s'];else if(type==='category')list=options.value.categories.filter(x=>x.is_active);else if(type==='subcategory')list=(options.value.categories.find(x=>x.id==form.value.product_category_id)?.subcategories||[]).filter(x=>x.is_active);else if(type==='uom')list=options.value.units.filter(x=>x.is_active);else if(type==='document')return outstanding.value.map(x=>({value:x.id,label:x.number,meta:`Due ${Number(x.due).toLocaleString(undefined,{minimumFractionDigits:2})}`}));return list.map(x=>({value:x.id,label:x.name+(x.sku?` — ${x.sku}`:x.symbol?` (${x.symbol})`:''),meta:x.phone||x.email||''}))}
function create(){editing.value=null;defaults();showForm.value=true}function edit(row){editing.value=row.id;form.value={...row};showForm.value=true}
async function loadOutstanding(){outstanding.value=[];paymentContext.value=null;form.value.document_id='';if(props.resource!=='payments')return;const partyId=form.value.payment_type==='supplier_payment'?form.value.supplier_id:form.value.customer_id;if(!partyId)return;contextLoading.value=true;try{const context=(await api.get('/payments/context',{params:{payment_type:form.value.payment_type,party_id:partyId}})).data.data;paymentContext.value=context;outstanding.value=context.outstanding||[]}catch(e){error.value=e.response?.data?.message||'Unable to load party balance history.'}finally{contextLoading.value=false}}
function selectOutstanding(value){const document=outstanding.value.find(item=>String(item.id)===String(value));if(document)form.value.amount=Math.min(Number(document.due),Number(paymentContext.value?.summary?.outstanding_balance??document.due))}
function money(value){return 'PKR '+Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function shortDate(value){return new Date(value).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}
async function save(){error.value='';notice.value='';try{let endpoint='/'+(props.resource==='payments'?voucherEndpoint.value:props.resource);if(props.resource==='stock-movements')endpoint='/stock-adjustments';const payload={...form.value};if(props.resource==='payments'){payload.payment_type=props.paymentType||payload.payment_type;if(payload.document_id)payload[payload.payment_type==='supplier_payment'?'purchase_id':'sale_id']=payload.document_id}delete payload.document_id;if(editing.value)await api.put(endpoint+'/'+editing.value,payload);else await api.post(endpoint,payload);showForm.value=false;notice.value=editing.value?'Record updated successfully.':props.paymentType==='supplier_payment'?'Payment voucher created successfully.':props.paymentType==='customer_payment'?'Receipt voucher created successfully.':'Record created successfully.';await load();setTimeout(()=>notice.value='',4000)}catch(e){error.value=Object.values(e.response?.data?.errors||{}).flat().join(' ')||e.response?.data?.message||'Unable to save.'}}
function go(target){if(target<1||target>pagination.value.last_page||target===page.value)return;page.value=target;load()}
watch([()=>props.resource,()=>props.paymentType],()=>{showForm.value=false;detailId.value=null;page.value=1;defaults();load();loadOptions()});watch(search,()=>{clearTimeout(timer.value);page.value=1;timer.value=setTimeout(load,300)});onMounted(()=>{defaults();const flash=sessionStorage.getItem('transaction_notice');if(flash){notice.value=flash;sessionStorage.removeItem('transaction_notice');setTimeout(()=>notice.value='',4000)}load();loadOptions()});
</script>
<template>
<div class="page-head"><div><span class="eyebrow">{{paymentType==='supplier_payment'?'Money out':paymentType==='customer_payment'?'Money in':'Records'}}</span><h1>{{pageTitle}}</h1><p class="page-subtitle">{{pageDescription}}</p></div><div class="page-actions"><RouterLink v-if="(resource==='purchases'||resource==='sales')&&canTransactionCreate" class="btn with-icon" :to="`/${resource}/new`"><AppIcon name="plus"/>New {{resource.slice(0,-1)}}</RouterLink><button v-if="canForm" class="with-icon" @click="create"><AppIcon name="plus"/>{{resource==='stock-movements'?'New adjustment':paymentType==='supplier_payment'?'New payment voucher':paymentType==='customer_payment'?'New receipt voucher':'New record'}}</button></div></div>
<div v-if="notice" class="success-message">{{notice}}</div><div v-if="error&&!showForm" class="error">{{error}}</div>
<form v-if="showForm" class="panel record-form" @submit.prevent="save"><div class="panel-head"><div><h2>{{editing?'Edit':paymentType==='supplier_payment'?'Create payment voucher':paymentType==='customer_payment'?'Create receipt voucher':'Create record'}}</h2><p>{{paymentType==='supplier_payment'?'Record a transfer out to a supplier.':paymentType==='customer_payment'?'Record a transfer received from a customer.':'Complete the required information below.'}}</p></div><button type="button" class="icon-only secondary" @click="showForm=false"><AppIcon name="close"/></button></div><div v-if="error" class="error">{{error}}</div><div class="form-grid"><div class="field" v-for="[key,label,type] in configs[resource]" v-show="!((key==='payment_type'&&paymentType)||(key==='supplier_id'&&form.payment_type!=='supplier_payment')||(key==='customer_id'&&form.payment_type!=='customer_payment'))"><label>{{label}}</label>
<SearchSelect v-if="type==='supplier'||type==='customer'||type==='product'" v-model="form[key]" :options="searchOptions(type)" :placeholder="`Type ${type} name…`" :required="type==='product'||(type==='supplier'&&form.payment_type==='supplier_payment')||(type==='customer'&&form.payment_type==='customer_payment')" @change="loadOutstanding"/>
<SearchSelect v-else-if="type==='category'" v-model="form[key]" :options="searchOptions(type)" placeholder="Type category name…" @change="form.product_subcategory_id=''"/>
<SearchSelect v-else-if="type==='subcategory'" v-model="form[key]" :options="searchOptions(type)" placeholder="Type subcategory name…" :disabled="!form.product_category_id"/>
<SearchSelect v-else-if="type==='uom'" v-model="form[key]" :options="searchOptions(type)" placeholder="Type unit name or symbol…" required/>
<select v-else-if="type==='payment_type'" v-model="form[key]" @change="form.supplier_id='';form.customer_id='';loadOutstanding()"><option value="supplier_payment">Transfer out — Payment voucher</option><option value="customer_payment">Transfer in — Receipt voucher</option></select>
<SearchSelect v-else-if="type==='document'" v-model="form[key]" :options="searchOptions(type)" placeholder="Type voucher number or leave general…" @change="selectOutstanding"/>
<select v-else-if="type==='payment_method'" v-model="form[key]"><option value="cash">Cash {{form.payment_type==='supplier_payment'?'out':'in'}}</option><option value="bank_transfer">Bank transfer {{form.payment_type==='supplier_payment'?'out':'in'}}</option><option value="card">Card</option><option value="other">Other</option></select>
<select v-else-if="type==='adjustment_type'" v-model="form[key]"><option value="increase">Increase stock</option><option value="decrease">Decrease stock</option></select>
<input v-else v-model="form[key]" :type="type" :step="type==='number'?'.001':undefined" required></div></div>
<div v-if="resource==='payments'&&contextLoading" class="payment-context-loading">Loading party balance and history…</div>
<section v-if="resource==='payments'&&paymentContext" class="payment-context" :class="paymentContext.summary.direction">
 <div class="payment-context-head"><div><span class="payment-direction">{{paymentContext.summary.direction_label}}</span><h3>{{paymentContext.party.name}}</h3><p>{{paymentContext.summary.direction==='transfer_out'?'Company pays this supplier':'Company receives from this customer'}} · {{paymentContext.party.phone||paymentContext.party.email||'No contact details'}}</p></div><div class="party-balance"><span>Current balance due</span><strong>{{money(paymentContext.summary.outstanding_balance)}}</strong><small>{{paymentContext.summary.open_documents}} open transaction{{paymentContext.summary.open_documents===1?'':'s'}}</small></div></div>
 <div class="payment-balance-grid"><div><span>Opening balance</span><strong>{{money(paymentContext.summary.opening_balance)}}</strong></div><div><span>{{form.payment_type==='supplier_payment'?'Total purchases':'Total sales'}}</span><strong>{{money(paymentContext.summary.billed_total)}}</strong></div><div><span>{{form.payment_type==='supplier_payment'?'Paid to supplier':'Received from customer'}}</span><strong>{{money(paymentContext.summary.settled_total)}}</strong></div></div>
 <div class="payment-history-grid"><div><div class="payment-subhead"><strong>Outstanding transactions</strong><span>Click one to fill its due amount</span></div><div class="payment-mini-table"><table><thead><tr><th>Document</th><th>Date</th><th class="number">Total</th><th class="number">Paid</th><th class="number">Due</th></tr></thead><tbody><tr v-for="item in paymentContext.outstanding" :key="item.id" :class="{selected:String(form.document_id)===String(item.id)}" @click="form.document_id=item.id;selectOutstanding(item.id)"><td><strong>{{item.number}}</strong></td><td>{{shortDate(item.date)}}</td><td class="number">{{money(item.total)}}</td><td class="number">{{money(item.paid)}}</td><td class="number"><strong>{{money(item.due)}}</strong></td></tr><tr v-if="!paymentContext.outstanding.length"><td colspan="5" class="empty-state">No outstanding transactions.</td></tr></tbody></table></div></div>
 <div><div class="payment-subhead"><strong>Recent balance history</strong><span>Newest activity first</span></div><div class="payment-mini-table"><table><thead><tr><th>Date / reference</th><th>Activity</th><th class="number">Change</th><th class="number">Balance</th></tr></thead><tbody><tr v-for="item in paymentContext.history" :key="`${item.type}-${item.id}`"><td><strong>{{item.number}}</strong><small>{{shortDate(item.date)}}</small></td><td>{{item.type}}<small>{{item.description}}</small></td><td class="number" :class="item.increase?'balance-increase':'balance-decrease'">{{item.increase?'+':'−'}} {{money(item.increase||item.decrease)}}</td><td class="number"><strong>{{money(item.running_balance)}}</strong></td></tr><tr v-if="!paymentContext.history.length"><td colspan="4" class="empty-state">No previous activity.</td></tr></tbody></table></div></div></div>
</section>
<div class="form-actions"><button class="with-icon"><AppIcon name="plus"/>{{resource==='payments'?(form.payment_type==='supplier_payment'?'Create payment voucher':'Create receipt voucher'):'Save record'}}</button><button type="button" class="secondary" @click="showForm=false">Cancel</button></div></form>
<div class="toolbar search-box"><AppIcon name="search"/><input v-model="search" placeholder="Search records…"></div>
<div class="panel list-panel"><div class="table-loading" v-if="loading">Loading records…</div><table><thead><tr><th v-for="c in columns">{{heading(c)}}</th><th v-if="detailResource||canEdit">Actions</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td v-for="c in columns"><span v-if="c.includes('status')||c==='is_reversed'" class="status" :class="r[c]==='paid'||r[c]==='completed'||r[c]===false?'success':r[c]==='partial'?'warning':'neutral'">{{c==='is_reversed'?(r[c]?'Reversed':'Active'):r[c]}}</span><template v-else>{{value(r,c)}}</template></td><td v-if="detailResource||canEdit"><div class="row-actions"><button v-if="detailResource" class="icon-only secondary" title="View and print" @click="detailId=r.id"><AppIcon name="eye"/></button><button v-if="canEdit&&['products','suppliers','customers'].includes(resource)" class="icon-only secondary" title="Edit" @click="edit(r)"><AppIcon name="edit"/></button></div></td></tr><tr v-if="!loading&&!rows.length"><td :colspan="columns.length+1"><div class="empty-state"><strong>No records found</strong><span>Try changing your search or create a new record.</span></div></td></tr></tbody></table><div class="pagination" v-if="pagination.last_page>1"><span>Showing {{pagination.from}}–{{pagination.to}} of {{pagination.total}}</span><div><button class="secondary" :disabled="page===1" @click="go(page-1)">Previous</button><span>Page {{page}} of {{pagination.last_page}}</span><button class="secondary" :disabled="page===pagination.last_page" @click="go(page+1)">Next</button></div></div></div>
<TransactionDetailModal v-if="detailId" :resource="resource" :api-resource="resource==='payments'?voucherEndpoint:resource" :id="detailId" @close="detailId=null"/>
</template>
