<script setup>
import {onMounted,ref} from 'vue';
import api from '../services/api';
import AppIcon from '../components/common/AppIcon.vue';
const categories=ref([]),loading=ref(true),saving=ref(false),error=ref(''),notice=ref('');
const category=ref({id:null,name:'',is_active:true}),subcategory=ref({id:null,product_category_id:'',name:'',is_active:true});
async function load(){loading.value=true;try{categories.value=(await api.get('/product-categories')).data.data}catch(e){error.value=e.response?.data?.message||'Unable to load categories.'}finally{loading.value=false}}
function resetCategory(){category.value={id:null,name:'',is_active:true}}function resetSubcategory(){subcategory.value={id:null,product_category_id:'',name:'',is_active:true}}
async function saveCategory(){saving.value=true;error.value='';try{const request=category.value.id?api.put(`/product-categories/${category.value.id}`,category.value):api.post('/product-categories',category.value);notice.value=(await request).data.message;resetCategory();await load()}catch(e){error.value=Object.values(e.response?.data?.errors||{}).flat().join(' ')||e.response?.data?.message}finally{saving.value=false}}
async function saveSubcategory(){saving.value=true;error.value='';try{const request=subcategory.value.id?api.put(`/product-categories/subcategories/${subcategory.value.id}`,subcategory.value):api.post('/product-categories/subcategories',subcategory.value);notice.value=(await request).data.message;resetSubcategory();await load()}catch(e){error.value=Object.values(e.response?.data?.errors||{}).flat().join(' ')||e.response?.data?.message}finally{saving.value=false}}
async function remove(type,item){if(!confirm(`Delete ${item.name}?`))return;error.value='';try{notice.value=(await api.delete(type==='category'?`/product-categories/${item.id}`:`/product-categories/subcategories/${item.id}`)).data.message;await load()}catch(e){error.value=Object.values(e.response?.data?.errors||{}).flat().join(' ')||e.response?.data?.message}}
onMounted(load);
</script>
<template><div class="page-head"><div><span class="eyebrow">Configuration</span><h1>Product categories</h1><p class="page-subtitle">Organize the product catalogue with categories and dependent subcategories.</p></div></div><div v-if="notice" class="success-message">{{notice}}</div><div v-if="error" class="error">{{error}}</div>
<div class="category-config-grid"><section class="panel category-form-card"><div class="panel-head"><div><h2>{{category.id?'Edit':'New'}} category</h2><p>Create the top level of your catalogue.</p></div></div><form @submit.prevent="saveCategory"><div class="field"><label>Category name</label><input v-model.trim="category.name" required maxlength="100" placeholder="e.g. Electronics"></div><label class="switch-row"><div><strong>Active</strong><span>Available when assigning products</span></div><input v-model="category.is_active" type="checkbox"><i></i></label><div class="form-actions"><button :disabled="saving">{{category.id?'Update':'Add'}} category</button><button v-if="category.id" type="button" class="secondary" @click="resetCategory">Cancel</button></div></form></section>
<section class="panel category-form-card"><div class="panel-head"><div><h2>{{subcategory.id?'Edit':'New'}} subcategory</h2><p>Place a more specific group under a category.</p></div></div><form @submit.prevent="saveSubcategory"><div class="field"><label>Parent category</label><select v-model="subcategory.product_category_id" required><option value="">Select category…</option><option v-for="c in categories.filter(x=>x.is_active)" :value="c.id">{{c.name}}</option></select></div><div class="field"><label>Subcategory name</label><input v-model.trim="subcategory.name" required maxlength="100" placeholder="e.g. Mobile phones"></div><label class="switch-row"><div><strong>Active</strong><span>Available when assigning products</span></div><input v-model="subcategory.is_active" type="checkbox"><i></i></label><div class="form-actions"><button :disabled="saving">{{subcategory.id?'Update':'Add'}} subcategory</button><button v-if="subcategory.id" type="button" class="secondary" @click="resetSubcategory">Cancel</button></div></form></section></div>
<section class="panel category-directory"><div class="panel-head"><div><h2>Catalogue structure</h2><p>{{categories.length}} categor{{categories.length===1?'y':'ies'}} configured</p></div></div><div v-if="loading" class="empty-state">Loading categories…</div><div v-else class="category-list"><article v-for="c in categories" :key="c.id"><div class="category-row"><div class="category-symbol">{{c.name.slice(0,2).toUpperCase()}}</div><div><strong>{{c.name}}</strong><span>{{c.products_count}} product{{c.products_count===1?'':'s'}} · {{c.subcategories.length}} subcategor{{c.subcategories.length===1?'y':'ies'}}</span></div><span class="status" :class="c.is_active?'success':'neutral'">{{c.is_active?'Active':'Inactive'}}</span><div class="row-actions"><button class="icon-only secondary" title="Edit" @click="category={id:c.id,name:c.name,is_active:c.is_active}"><AppIcon name="edit"/></button><button class="icon-only secondary danger-button" title="Delete" @click="remove('category',c)"><AppIcon name="close"/></button></div></div><div class="subcategory-list"><div v-for="s in c.subcategories" :key="s.id"><span class="subcategory-line"></span><div><strong>{{s.name}}</strong><small>{{s.is_active?'Active':'Inactive'}}</small></div><div class="row-actions"><button class="icon-only secondary" title="Edit" @click="subcategory={id:s.id,product_category_id:c.id,name:s.name,is_active:s.is_active}"><AppIcon name="edit"/></button><button class="icon-only secondary danger-button" title="Delete" @click="remove('subcategory',s)"><AppIcon name="close"/></button></div></div><div v-if="!c.subcategories.length" class="no-subcategories">No subcategories yet</div></div></article><div v-if="!categories.length" class="empty-state">Create your first product category above.</div></div></section></template>
