<script setup>
import {onMounted,ref} from 'vue';
import api from '../services/api';
import AppIcon from '../components/common/AppIcon.vue';
const categories=ref([]),units=ref([]),loading=ref(true),saving=ref(false),error=ref(''),notice=ref('');
const category=ref({id:null,name:'',is_active:true}),subcategory=ref({id:null,product_category_id:'',name:'',is_active:true});
const unit=ref({id:null,name:'',symbol:'',decimal_places:3,is_active:true});
async function load(){loading.value=true;try{const [categoryResponse,unitResponse]=await Promise.all([api.get('/product-categories'),api.get('/units-of-measurement')]);categories.value=categoryResponse.data.data;units.value=unitResponse.data.data}catch(e){error.value=e.response?.data?.message||'Unable to load product settings.'}finally{loading.value=false}}
function resetCategory(){category.value={id:null,name:'',is_active:true}}function resetSubcategory(){subcategory.value={id:null,product_category_id:'',name:'',is_active:true}}
async function saveCategory(){saving.value=true;error.value='';try{const request=category.value.id?api.put(`/product-categories/${category.value.id}`,category.value):api.post('/product-categories',category.value);notice.value=(await request).data.message;resetCategory();await load()}catch(e){error.value=Object.values(e.response?.data?.errors||{}).flat().join(' ')||e.response?.data?.message}finally{saving.value=false}}
async function saveSubcategory(){saving.value=true;error.value='';try{const request=subcategory.value.id?api.put(`/product-categories/subcategories/${subcategory.value.id}`,subcategory.value):api.post('/product-categories/subcategories',subcategory.value);notice.value=(await request).data.message;resetSubcategory();await load()}catch(e){error.value=Object.values(e.response?.data?.errors||{}).flat().join(' ')||e.response?.data?.message}finally{saving.value=false}}
async function remove(type,item){if(!confirm(`Delete ${item.name}?`))return;error.value='';try{notice.value=(await api.delete(type==='category'?`/product-categories/${item.id}`:`/product-categories/subcategories/${item.id}`)).data.message;await load()}catch(e){error.value=Object.values(e.response?.data?.errors||{}).flat().join(' ')||e.response?.data?.message}}
function resetUnit(){unit.value={id:null,name:'',symbol:'',decimal_places:3,is_active:true}}
async function saveUnit(){saving.value=true;error.value='';try{const request=unit.value.id?api.put(`/units-of-measurement/${unit.value.id}`,unit.value):api.post('/units-of-measurement',unit.value);notice.value=(await request).data.message;resetUnit();await load()}catch(e){error.value=Object.values(e.response?.data?.errors||{}).flat().join(' ')||e.response?.data?.message}finally{saving.value=false}}
async function removeUnit(item){if(!confirm(`Delete ${item.name}?`))return;error.value='';try{notice.value=(await api.delete(`/units-of-measurement/${item.id}`)).data.message;await load()}catch(e){error.value=Object.values(e.response?.data?.errors||{}).flat().join(' ')||e.response?.data?.message}}
onMounted(load);
</script>
<template><div class="page-head"><div><span class="eyebrow">Configuration</span><h1>Product settings</h1><p class="page-subtitle">Manage units of measurement, categories, and dependent subcategories.</p></div></div><div v-if="notice" class="success-message">{{notice}}</div><div v-if="error" class="error">{{error}}</div>
<div class="uom-settings-grid"><section class="panel category-form-card"><div class="panel-head"><div><h2>{{unit.id?'Edit':'New'}} unit of measurement</h2><p>Configure how product quantities are recorded.</p></div></div><form @submit.prevent="saveUnit"><div class="form-grid"><div class="field"><label>Unit name</label><input v-model.trim="unit.name" required maxlength="80" placeholder="e.g. Kilogram"></div><div class="field"><label>Symbol</label><input v-model.trim="unit.symbol" required maxlength="20" placeholder="kg"></div><div class="field"><label>Decimal places</label><select v-model.number="unit.decimal_places"><option :value="0">0 — whole units</option><option :value="1">1</option><option :value="2">2</option><option :value="3">3</option></select></div></div><label class="switch-row"><div><strong>Active</strong><span>Available when creating products</span></div><input v-model="unit.is_active" type="checkbox"><i></i></label><div class="form-actions"><button :disabled="saving">{{unit.id?'Update':'Add'}} unit</button><button v-if="unit.id" type="button" class="secondary" @click="resetUnit">Cancel</button></div></form></section><section class="panel uom-directory"><div class="panel-head"><div><h2>Configured units</h2><p>{{units.length}} measurement unit{{units.length===1?'':'s'}}</p></div></div><div class="uom-list"><div v-for="u in units" :key="u.id"><span class="uom-symbol">{{u.symbol}}</span><div><strong>{{u.name}}</strong><small>{{u.decimal_places}} decimal place{{u.decimal_places===1?'':'s'}} · {{u.products_count}} products</small></div><span class="status" :class="u.is_active?'success':'neutral'">{{u.is_active?'Active':'Inactive'}}</span><div class="row-actions"><button class="icon-only secondary" @click="unit={...u}"><AppIcon name="edit"/></button><button class="icon-only secondary danger-button" @click="removeUnit(u)"><AppIcon name="close"/></button></div></div></div></section></div>
<div class="category-config-grid"><section class="panel category-form-card"><div class="panel-head"><div><h2>{{category.id?'Edit':'New'}} category</h2><p>Create the top level of your catalogue.</p></div></div><form @submit.prevent="saveCategory"><div class="field"><label>Category name</label><input v-model.trim="category.name" required maxlength="100" placeholder="e.g. Electronics"></div><label class="switch-row"><div><strong>Active</strong><span>Available when assigning products</span></div><input v-model="category.is_active" type="checkbox"><i></i></label><div class="form-actions"><button :disabled="saving">{{category.id?'Update':'Add'}} category</button><button v-if="category.id" type="button" class="secondary" @click="resetCategory">Cancel</button></div></form></section>
<section class="panel category-form-card"><div class="panel-head"><div><h2>{{subcategory.id?'Edit':'New'}} subcategory</h2><p>Place a more specific group under a category.</p></div></div><form @submit.prevent="saveSubcategory"><div class="field"><label>Parent category</label><select v-model="subcategory.product_category_id" required><option value="">Select category…</option><option v-for="c in categories.filter(x=>x.is_active)" :value="c.id">{{c.name}}</option></select></div><div class="field"><label>Subcategory name</label><input v-model.trim="subcategory.name" required maxlength="100" placeholder="e.g. Mobile phones"></div><label class="switch-row"><div><strong>Active</strong><span>Available when assigning products</span></div><input v-model="subcategory.is_active" type="checkbox"><i></i></label><div class="form-actions"><button :disabled="saving">{{subcategory.id?'Update':'Add'}} subcategory</button><button v-if="subcategory.id" type="button" class="secondary" @click="resetSubcategory">Cancel</button></div></form></section></div>
<section class="panel category-directory"><div class="panel-head"><div><h2>Catalogue structure</h2><p>{{categories.length}} categor{{categories.length===1?'y':'ies'}} configured</p></div></div><div v-if="loading" class="empty-state">Loading categories…</div><div v-else class="category-list"><article v-for="c in categories" :key="c.id"><div class="category-row"><div class="category-symbol">{{c.name.slice(0,2).toUpperCase()}}</div><div><strong>{{c.name}}</strong><span>{{c.products_count}} product{{c.products_count===1?'':'s'}} · {{c.subcategories.length}} subcategor{{c.subcategories.length===1?'y':'ies'}}</span></div><span class="status" :class="c.is_active?'success':'neutral'">{{c.is_active?'Active':'Inactive'}}</span><div class="row-actions"><button class="icon-only secondary" title="Edit" @click="category={id:c.id,name:c.name,is_active:c.is_active}"><AppIcon name="edit"/></button><button class="icon-only secondary danger-button" title="Delete" @click="remove('category',c)"><AppIcon name="close"/></button></div></div><div class="subcategory-list"><div v-for="s in c.subcategories" :key="s.id"><span class="subcategory-line"></span><div><strong>{{s.name}}</strong><small>{{s.is_active?'Active':'Inactive'}}</small></div><div class="row-actions"><button class="icon-only secondary" title="Edit" @click="subcategory={id:s.id,product_category_id:c.id,name:s.name,is_active:s.is_active}"><AppIcon name="edit"/></button><button class="icon-only secondary danger-button" title="Delete" @click="remove('subcategory',s)"><AppIcon name="close"/></button></div></div><div v-if="!c.subcategories.length" class="no-subcategories">No subcategories yet</div></div></article><div v-if="!categories.length" class="empty-state">Create your first product category above.</div></div></section></template>
