<script setup>
import {computed,onMounted,ref,watch} from 'vue';import api from '../services/api';
import AppIcon from '../components/common/AppIcon.vue';
const reports=[['stock','Stock report','Inventory valuation and availability'],['low-stock','Low-stock report','Products requiring attention'],['purchases','Purchase report','Supplier purchasing and payables'],['sales','Sales report','Customer sales and receivables'],['profit','Profit report','Revenue, cost, and gross margin']];
const type=ref('stock'),rows=ref([]),summary=ref({}),loading=ref(false),error=ref(''),options=ref({suppliers:[],customers:[],products:[]});
const today=new Date().toISOString().slice(0,10),monthStart=new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10);
const filters=ref({date_from:monthStart,date_to:today,supplier_id:'',customer_id:'',product_id:'',payment_status:'',status:'',search:''});
const definition=computed(()=>reports.find(r=>r[0]===type.value)),transactional=computed(()=>['purchases','sales','profit'].includes(type.value));
const columns=computed(()=>rows.value.length?Object.keys(rows.value[0]):[]);
const moneyKeys=['average_cost','sale_price','stock_value','grand_total','paid','due','revenue','cogs','gross_profit'];
const cards=computed(()=>Object.entries(summary.value).map(([key,value])=>({key,label:key.replaceAll('_',' '),value:moneyKeys.some(k=>key.includes(k))?'PKR '+Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):key.includes('percent')?`${value}%`:Number(value||0).toLocaleString()})));
async function load(){loading.value=true;error.value='';try{const {data}=await api.get('/reports/'+type.value,{params:filters.value});rows.value=data.data.rows||[];summary.value=data.data.summary||{}}catch(e){error.value=e.response?.data?.message||'Unable to load report.'}finally{loading.value=false}}
async function optionsLoad(){for(const r of ['suppliers','customers','products'])options.value[r]=(await api.get('/'+r,{params:{per_page:100,active:1}})).data.data.data}
function reset(){filters.value={date_from:monthStart,date_to:today,supplier_id:'',customer_id:'',product_id:'',payment_status:'',status:'',search:''};load()}
function printReport(){window.print()}
function csv(){if(!rows.value.length)return;const escape=v=>`"${String(v??'').replaceAll('"','""')}"`;const content=[columns.value.map(escape).join(','),...rows.value.map(r=>columns.value.map(c=>escape(r[c])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'text/csv'}));a.download=`${type.value}-report-${today}.csv`;a.click();URL.revokeObjectURL(a.href)}
function format(value,key){if(moneyKeys.includes(key))return 'PKR '+Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});if(key==='margin_percent')return value+'%';if(['current_stock','minimum_stock'].includes(key))return Number(value).toLocaleString(undefined,{maximumFractionDigits:3});return value}
watch(type,()=>{filters.value.payment_status='';filters.value.status='';load()});onMounted(()=>{optionsLoad();load()});
</script>
<template><div class="page-head"><div><span class="eyebrow">Analysis workspace</span><h1>Reports</h1><p class="page-subtitle">{{definition?.[2]}}</p></div><div class="report-actions"><button class="secondary with-icon" @click="printReport"><AppIcon name="print"/>Print</button><button class="with-icon" @click="csv"><AppIcon name="download"/>Export CSV</button></div></div>
<div class="report-tabs"><button v-for="[key,label] in reports" :key="key" :class="{active:type===key}" @click="type=key">{{label}}</button></div>
<section class="panel filter-panel"><div class="filter-grid"><div class="field" v-if="!transactional"><label>Search products</label><input v-model="filters.search" placeholder="Name or SKU"></div><template v-if="transactional"><div class="field"><label>From</label><input v-model="filters.date_from" type="date"></div><div class="field"><label>To</label><input v-model="filters.date_to" type="date"></div></template>
<div class="field" v-if="type==='purchases'"><label>Supplier</label><select v-model="filters.supplier_id"><option value="">All suppliers</option><option v-for="x in options.suppliers" :value="x.id">{{x.name}}</option></select></div>
<div class="field" v-if="type==='sales'||type==='profit'"><label>Customer</label><select v-model="filters.customer_id"><option value="">All customers</option><option v-for="x in options.customers" :value="x.id">{{x.name}}</option></select></div>
<div class="field" v-if="type==='purchases'||type==='sales'"><label>Product</label><select v-model="filters.product_id"><option value="">All products</option><option v-for="x in options.products" :value="x.id">{{x.name}}</option></select></div>
<div class="field" v-if="type==='purchases'||type==='sales'"><label>Payment</label><select v-model="filters.payment_status"><option value="">All statuses</option><option value="paid">Paid</option><option value="partial">Partial</option><option value="unpaid">Unpaid</option></select></div>
<div class="field" v-if="type==='stock'||type==='low-stock'"><label>Stock status</label><select v-model="filters.status"><option value="">All stock</option><option value="in_stock">In stock</option><option value="low">Low stock</option><option value="out">Out of stock</option></select></div>
<div class="filter-actions"><button class="with-icon" @click="load"><AppIcon name="search"/>Apply filters</button><button class="secondary" @click="reset">Reset</button></div></div></section>
<div v-if="error" class="error">{{error}}</div><div class="report-summary"><div class="summary-card" v-for="card in cards" :key="card.key"><span>{{card.label}}</span><strong>{{card.value}}</strong></div></div>
<section class="panel report-table"><div class="panel-head"><div><h2>{{definition?.[1]}}</h2><p>{{rows.length}} matching records</p></div><span class="generated-at">Updated {{new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}}</span></div><div class="table-wrap"><table><thead><tr><th v-for="c in columns" :class="{number:moneyKeys.includes(c)||c.includes('stock')||c.includes('percent')}">{{c.replaceAll('_',' ')}}</th></tr></thead><tbody><tr v-for="(r,i) in rows" :key="i"><td v-for="c in columns" :class="{number:moneyKeys.includes(c)||c.includes('stock')||c.includes('percent')}"><span v-if="c.includes('status')" class="status" :class="String(r[c]).toLowerCase().includes('paid')||r[c]==='In stock'?'success':String(r[c]).toLowerCase().includes('low')||String(r[c]).toLowerCase().includes('partial')?'warning':'neutral'">{{r[c]}}</span><template v-else>{{format(r[c],c)}}</template></td></tr><tr v-if="!loading&&!rows.length"><td :colspan="columns.length||1"><div class="empty-state">No records match the selected filters.</div></td></tr></tbody></table><div v-if="loading" class="loading-overlay">Loading report…</div></div></section>
</template>
