<script setup>
import {computed,onMounted,ref,watch} from 'vue';import api from '../services/api';
import AppIcon from '../components/common/AppIcon.vue';
import SearchSelect from '../components/common/SearchSelect.vue';
import {can} from '../services/auth';
const reports=[['financial','Financial position','Cash and bank movement, expenses, receivables, and payables'],['expenses','Expense report','Operating costs by category and payment channel'],['stock-ledger','Product stock ledger','When each product entered or left inventory'],['stock','Stock report','Inventory valuation and availability'],['low-stock','Low-stock report','Products requiring attention'],['purchases','Purchase report','Supplier purchasing and payables'],['sales','Sales report','Customer sales and receivables'],['profit','Profit report','Revenue, cost, operating expenses, and net profit']];
const type=ref('financial'),scope=ref('company'),rows=ref([]),summary=ref({}),details=ref({receivables:[],payables:[]}),period=ref({}),loading=ref(false),error=ref(''),options=ref({suppliers:[],customers:[],products:[],expense_categories:[]});
const today=new Date().toISOString().slice(0,10),monthStart=new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10);
const filters=ref({date_from:monthStart,date_to:today,supplier_id:'',customer_id:'',product_id:'',expense_category_id:'',payment_status:'',payment_method:'',status:'',search:''});
const definition=computed(()=>reports.find(r=>r[0]===type.value)),transactional=computed(()=>['purchases','sales','expenses','profit','financial','stock-ledger'].includes(type.value));
const columns=computed(()=>rows.value.length?Object.keys(rows.value[0]):[]);
const moneyKeys=['average_cost','sale_price','stock_value','grand_total','paid','due','amount','total_amount','cash_total','bank_total','card_total','revenue','cogs','gross_profit','net_profit','operating_expenses','supplier_payments','received','net_movement','opening_balance','settled','outstanding','total_received','total_paid','net_cash_flow','cash_net_movement','bank_net_movement','customer_receivables','supplier_payables','net_working_balance'];
const cards=computed(()=>Object.entries(summary.value).map(([key,value])=>({key,label:key.replaceAll('_',' '),value:moneyKeys.some(k=>key.includes(k))?'PKR '+Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):key.includes('percent')?`${value}%`:Number(value||0).toLocaleString()})));
async function load(){loading.value=true;error.value='';try{const endpoint=scope.value==='group'?'/reports-consolidated/':'/reports/';const {data}=await api.get(endpoint+type.value,{params:filters.value});rows.value=(data.data.rows||[]).map((row,index)=>({serial:index+1,...row}));summary.value=data.data.summary||{};details.value=data.data.details||{receivables:[],payables:[]};period.value=data.data.period||{}}catch(e){error.value=e.response?.data?.message||'Unable to load report.'}finally{loading.value=false}}
async function optionsLoad(){for(const r of ['suppliers','customers','products'])options.value[r]=(await api.get('/'+r,{params:{per_page:100,active:1}})).data.data.data;if(can('expenses.view'))options.value.expense_categories=(await api.get('/expenses/categories')).data.data}
function reset(){filters.value={date_from:monthStart,date_to:today,supplier_id:'',customer_id:'',product_id:'',expense_category_id:'',payment_status:'',payment_method:'',status:'',search:''};load()}
function printReport(){window.print()}
function csv(){if(!rows.value.length)return;const escape=v=>`"${String(v??'').replaceAll('"','""')}"`;const content=[columns.value.map(escape).join(','),...rows.value.map(r=>columns.value.map(c=>escape(r[c])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'text/csv'}));a.download=`${type.value}-report-${today}.csv`;a.click();URL.revokeObjectURL(a.href)}
function format(value,key){if(moneyKeys.includes(key))return 'PKR '+Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});if(key==='margin_percent')return value+'%';if(['current_stock','minimum_stock','quantity_in','quantity_out','stock_before','stock_after'].includes(key))return Number(value).toLocaleString(undefined,{maximumFractionDigits:3});return value}
const searchable=list=>(list||[]).map(item=>({value:item.id,label:item.name+(item.sku?` — ${item.sku}`:''),meta:item.phone||item.email||''}));
watch(type,()=>{filters.value.payment_status='';filters.value.status='';filters.value.expense_category_id='';load()});watch(scope,()=>{filters.value.supplier_id='';filters.value.customer_id='';filters.value.product_id='';filters.value.expense_category_id='';load()});onMounted(()=>{optionsLoad();load()});
</script>
<template><div class="page-head"><div><span class="eyebrow">Analysis workspace</span><h1>Reports</h1><p class="page-subtitle">{{definition?.[2]}}</p></div><div class="report-actions"><button class="secondary with-icon" @click="printReport"><AppIcon name="print"/>Print</button><button class="with-icon" @click="csv"><AppIcon name="download"/>Export CSV</button></div></div>
<div class="report-tabs"><button v-for="[key,label] in reports" :key="key" :class="{active:type===key}" @click="type=key">{{label}}</button></div>
<section class="panel filter-panel"><div class="filter-grid"><div v-if="can('reports.consolidated')" class="field"><label>Reporting scope</label><select v-model="scope"><option value="company">Selected company</option><option value="group">Consolidated group</option></select></div><div class="field" v-if="!transactional"><label>Search products</label><input v-model="filters.search" placeholder="Name or SKU"></div><template v-if="transactional"><div class="field"><label>From</label><input v-model="filters.date_from" type="date"></div><div class="field"><label>To</label><input v-model="filters.date_to" type="date"></div></template>
<div class="field" v-if="scope==='company'&&type==='purchases'"><label>Supplier</label><SearchSelect v-model="filters.supplier_id" :options="searchable(options.suppliers)" placeholder="Type supplier name…"/></div>
<div class="field" v-if="scope==='company'&&(type==='sales'||type==='profit')"><label>Customer</label><SearchSelect v-model="filters.customer_id" :options="searchable(options.customers)" placeholder="Type customer name…"/></div>
<div class="field" v-if="scope==='company'&&(type==='purchases'||type==='sales'||type==='stock-ledger')"><label>Product</label><SearchSelect v-model="filters.product_id" :options="searchable(options.products)" placeholder="Type product name or SKU…"/></div>
<div class="field" v-if="type==='purchases'||type==='sales'"><label>Payment</label><select v-model="filters.payment_status"><option value="">All statuses</option><option value="paid">Paid</option><option value="partial">Partial</option><option value="unpaid">Unpaid</option></select></div>
<div class="field" v-if="scope==='company'&&type==='expenses'"><label>Expense category</label><select v-model="filters.expense_category_id"><option value="">All categories</option><option v-for="category in options.expense_categories" :value="category.id">{{category.name}}</option></select></div>
<div class="field" v-if="type==='financial'||type==='expenses'"><label>Payment channel</label><select v-model="filters.payment_method"><option value="">All channels</option><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="other">Other</option></select></div>
<div class="field" v-if="type==='expenses'"><label>Status</label><select v-model="filters.status"><option value="">All statuses</option><option value="posted">Posted</option><option value="cancelled">Cancelled</option></select></div>
<div class="field" v-if="type==='stock'||type==='low-stock'"><label>Stock status</label><select v-model="filters.status"><option value="">All stock</option><option value="in_stock">In stock</option><option value="low">Low stock</option><option value="out">Out of stock</option></select></div>
<div class="filter-actions"><button class="with-icon" @click="load"><AppIcon name="search"/>Apply filters</button><button class="secondary" @click="reset">Reset</button></div></div></section>
<div v-if="error" class="error">{{error}}</div><div class="report-summary"><div class="summary-card" v-for="card in cards" :key="card.key"><span>{{card.label}}</span><strong>{{card.value}}</strong></div></div>
<section v-if="type==='financial'" class="financial-executive panel"><span class="eyebrow">Executive summary</span><p><strong>{{Number(summary.net_cash_flow||0)>=0?'Positive':'Negative'}} net cash movement of {{format(summary.net_cash_flow,'net_cash_flow')}}</strong> after {{format(summary.operating_expenses,'operating_expenses')}} in operating expenses. As of {{period.position_as_of||filters.date_to}}, customers owe {{format(summary.customer_receivables,'outstanding')}} and the business owes suppliers {{format(summary.supplier_payables,'outstanding')}}.</p></section>
<div v-if="type==='stock-ledger'&&summary.chronology_issues" class="inline-warning">{{summary.chronology_issues}} movement{{summary.chronology_issues===1?'':'s'}} produced a negative chronological balance. This normally means a sale was backdated before the purchase or opening stock that supplied it.</div>
<section class="panel report-table"><div class="panel-head"><div><h2>{{definition?.[1]}}</h2><p>{{rows.length}} matching records</p></div><span class="generated-at">Updated {{new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}}</span></div><div class="table-wrap"><table><thead><tr><th v-for="c in columns" :class="{number:moneyKeys.includes(c)||c.includes('stock')||c.includes('percent')}">{{c==='serial'?'S. No.':c.replaceAll('_',' ')}}</th></tr></thead><tbody><tr v-for="(r,i) in rows" :key="i"><td v-for="c in columns" :class="{number:moneyKeys.includes(c)||c.includes('stock')||c.includes('percent')}"><span v-if="c.includes('status')" class="status" :class="String(r[c]).toLowerCase().includes('paid')||r[c]==='In stock'?'success':String(r[c]).toLowerCase().includes('low')||String(r[c]).toLowerCase().includes('partial')?'warning':'neutral'">{{r[c]}}</span><template v-else>{{format(r[c],c)}}</template></td></tr><tr v-if="!loading&&!rows.length"><td :colspan="columns.length||1"><div class="empty-state">No records match the selected filters.</div></td></tr></tbody></table><div v-if="loading" class="loading-overlay">Loading report…</div></div></section>
<div v-if="type==='financial'" class="financial-detail-grid"><section class="panel financial-party-table"><div class="panel-head"><div><h2>Customer receivables</h2><p>Largest outstanding customer balances as of {{period.position_as_of}}</p></div></div><div class="table-wrap"><table><thead><tr><th v-if="scope==='group'">Company</th><th>Customer</th><th class="number">Sales</th><th class="number">Received</th><th class="number">Outstanding</th></tr></thead><tbody><tr v-for="r in details.receivables" :key="`${r.company||''}-${r.party}`"><td v-if="scope==='group'">{{r.company}}</td><td><strong>{{r.party}}</strong></td><td class="number">{{format(r.transactions,'grand_total')}}</td><td class="number">{{format(r.settled,'settled')}}</td><td class="number financial-outstanding">{{format(r.outstanding,'outstanding')}}</td></tr><tr v-if="!details.receivables.length"><td :colspan="scope==='group'?5:4" class="empty-state">No customer receivables.</td></tr></tbody></table></div></section><section class="panel financial-party-table"><div class="panel-head"><div><h2>Supplier payables</h2><p>Largest outstanding supplier balances as of {{period.position_as_of}}</p></div></div><div class="table-wrap"><table><thead><tr><th v-if="scope==='group'">Company</th><th>Supplier</th><th class="number">Purchases</th><th class="number">Paid</th><th class="number">Outstanding</th></tr></thead><tbody><tr v-for="r in details.payables" :key="`${r.company||''}-${r.party}`"><td v-if="scope==='group'">{{r.company}}</td><td><strong>{{r.party}}</strong></td><td class="number">{{format(r.transactions,'grand_total')}}</td><td class="number">{{format(r.settled,'settled')}}</td><td class="number financial-outstanding">{{format(r.outstanding,'outstanding')}}</td></tr><tr v-if="!details.payables.length"><td :colspan="scope==='group'?5:4" class="empty-state">No supplier payables.</td></tr></tbody></table></div></section></div>
</template>
