<script setup>
import {computed,onMounted,ref} from 'vue';
import {useRouter} from 'vue-router';
import api from '../services/api';
import AppIcon from '../components/common/AppIcon.vue';

const props=defineProps({type:String}),router=useRouter();
const products=ref([]),parties=ref([]),error=ref(''),saving=ref(false),loading=ref(true);
const isSale=computed(()=>props.type==='sales');
const today=new Date().toISOString().slice(0,10);
const form=ref({purchase_date:today,sale_date:today,supplier_id:'',customer_id:'',supplier_invoice_number:'',payment_method:'cash',discount:0,additional_cost:0,tax:0,paid_amount:0,notes:'',items:[]});
onMounted(async()=>{try{const [productResponse,partyResponse]=await Promise.all([api.get('/products',{params:{active:1,per_page:100}}),api.get(isSale.value?'/customers':'/suppliers',{params:{per_page:100}})]);products.value=productResponse.data.data.data;parties.value=partyResponse.data.data.data;add()}catch(e){error.value='Unable to load transaction options.'}finally{loading.value=false}});
function add(){form.value.items.push({product_id:'',quantity:1,unit_price:0,discount:0})}
function product(item){return products.value.find(p=>p.id==item.product_id)}
function choose(item){const selected=product(item);item.unit_price=Number(isSale.value?selected?.sale_price:selected?.purchase_price)||0}
function lineTotal(item){return Math.max(0,Number(item.quantity||0)*Number(item.unit_price||0)-Number(item.discount||0))}
const subtotal=computed(()=>form.value.items.reduce((sum,item)=>sum+lineTotal(item),0));
const total=computed(()=>Math.max(0,subtotal.value-Number(form.value.discount||0)+Number(isSale.value?form.value.tax:form.value.additional_cost||0)));
const due=computed(()=>Math.max(0,total.value-Number(form.value.paid_amount||0)));
const invalidStock=computed(()=>isSale.value&&form.value.items.some(item=>item.product_id&&Number(item.quantity)>Number(product(item)?.current_stock||0)));
const duplicateProducts=computed(()=>{const ids=form.value.items.map(i=>i.product_id).filter(Boolean);return new Set(ids).size!==ids.length});
const selectedParty=computed(()=>parties.value.find(p=>p.id==form.value[isSale.value?'customer_id':'supplier_id']));
const canSave=computed(()=>!saving.value&&!loading.value&&!invalidStock.value&&!duplicateProducts.value&&form.value.items.length>0&&form.value.items.every(i=>i.product_id&&Number(i.quantity)>0));
const money=value=>'PKR '+Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
async function save(){error.value='';saving.value=true;try{await api.post('/'+props.type,form.value);sessionStorage.setItem('transaction_notice',`${isSale.value?'Sale':'Purchase'} recorded successfully.`);router.push('/'+props.type)}catch(e){error.value=Object.values(e.response?.data?.errors||{}).flat().join(' ')||e.response?.data?.message||'Unable to save transaction.';window.scrollTo({top:0,behavior:'smooth'})}finally{saving.value=false}}
</script>
<template>
<div class="page-head"><div><span class="eyebrow">{{isSale?'Sales':'Procurement'}}</span><h1>New {{isSale?'sale':'purchase'}}</h1><p class="page-subtitle">{{isSale?'Create an invoice and reduce stock immediately.':'Record supplier stock and update weighted-average cost.'}}</p></div><RouterLink class="btn secondary with-icon" :to="`/${type}`"><AppIcon name="close"/>Close</RouterLink></div>
<div v-if="error" class="error transaction-error">{{error}}</div>
<div v-if="loading" class="panel empty-state">Loading products and {{isSale?'customers':'suppliers'}}…</div>
<form v-else class="transaction-layout" @submit.prevent="save">
<div class="transaction-main">
<section class="panel transaction-section"><div class="section-title"><span>1</span><div><h2>Transaction details</h2><p>Choose the party, date, and payment method.</p></div></div><div class="form-grid"><div class="field"><label>{{isSale?'Sale':'Purchase'}} date</label><input v-model="form[isSale?'sale_date':'purchase_date']" type="date" required></div><div class="field"><label>{{isSale?'Customer':'Supplier'}}</label><select v-model="form[isSale?'customer_id':'supplier_id']" required><option value="">Select {{isSale?'customer':'supplier'}}…</option><option v-for="party in parties" :value="party.id">{{party.name}}</option></select></div><div class="field"><label>Payment method</label><select v-model="form.payment_method"><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="other">Other</option></select></div><div v-if="!isSale" class="field"><label>Supplier invoice number <span>Optional</span></label><input v-model="form.supplier_invoice_number" placeholder="e.g. INV-1024"></div></div></section>
<section class="panel transaction-section item-section"><div class="section-title"><span>2</span><div><h2>Products</h2><p>Add products and confirm quantity, price, and discount.</p></div><button type="button" class="secondary with-icon section-action" @click="add"><AppIcon name="plus"/>Add product</button></div>
<div v-if="duplicateProducts" class="inline-warning">A product can only appear once in a transaction.</div><div class="transaction-table"><table><thead><tr><th>S. No.</th><th>Product</th><th v-if="isSale">Available</th><th class="number">Quantity</th><th class="number">Unit price</th><th class="number">Discount</th><th class="number">Line total</th><th></th></tr></thead><tbody><tr v-for="(item,index) in form.items" :key="index" :class="{invalid:item.product_id&&isSale&&Number(item.quantity)>Number(product(item)?.current_stock||0)}"><td>{{index+1}}</td><td class="product-select"><select v-model="item.product_id" @change="choose(item)" required><option value="">Search or select product…</option><option v-for="p in products" :value="p.id">{{p.name}} — {{p.sku}}</option></select><small v-if="product(item)">{{product(item).unit}} · {{isSale?'Sale':'Cost'}} {{money(item.unit_price)}}</small></td><td v-if="isSale"><span class="stock-badge" :class="{danger:Number(item.quantity)>Number(product(item)?.current_stock||0)}">{{Number(product(item)?.current_stock||0).toLocaleString(undefined,{maximumFractionDigits:3})}} {{product(item)?.unit||''}}</span></td><td><input v-model.number="item.quantity" class="number-input" type="number" min=".001" step=".001" required></td><td><input v-model.number="item.unit_price" class="number-input" type="number" min="0" step=".01" required></td><td><input v-model.number="item.discount" class="number-input" type="number" min="0" :max="Number(item.quantity||0)*Number(item.unit_price||0)" step=".01"></td><td class="number"><strong>{{money(lineTotal(item))}}</strong></td><td><button type="button" class="icon-only secondary danger-button" title="Remove item" @click="form.items.splice(index,1)"><AppIcon name="close"/></button></td></tr></tbody></table></div>
<button v-if="!form.items.length" type="button" class="empty-add" @click="add"><AppIcon name="plus"/>Add your first product</button></section>
<section class="panel transaction-section"><div class="section-title"><span>3</span><div><h2>Additional information</h2><p>Add optional notes for this transaction.</p></div></div><div class="field"><label>Notes <span>Optional</span></label><textarea v-model="form.notes" rows="3" placeholder="Delivery instructions, references, or internal notes…"></textarea></div></section>
</div>
<div class="transaction-summary"><section class="panel summary-panel"><div class="summary-heading"><div><span class="eyebrow">Summary</span><h2>{{isSale?'Sales invoice':'Purchase order'}}</h2></div><span class="status neutral">New</span></div><div class="party-preview"><span>{{isSale?'Customer':'Supplier'}}</span><strong>{{selectedParty?.name||`No ${isSale?'customer':'supplier'} selected`}}</strong></div><div class="summary-fields"><div class="field"><label>Header discount</label><input v-model.number="form.discount" type="number" min="0" :max="subtotal" step=".01"></div><div class="field"><label>{{isSale?'Tax':'Additional cost'}}</label><input v-model.number="form[isSale?'tax':'additional_cost']" type="number" min="0" step=".01"></div><div class="field"><label>Paid now</label><input v-model.number="form.paid_amount" type="number" min="0" :max="total" step=".01"></div></div><div class="summary-totals"><div><span>Items</span><strong>{{form.items.length}}</strong></div><div><span>Subtotal</span><strong>{{money(subtotal)}}</strong></div><div><span>Discount</span><strong>− {{money(form.discount)}}</strong></div><div><span>{{isSale?'Tax':'Additional cost'}}</span><strong>{{money(isSale?form.tax:form.additional_cost)}}</strong></div><div class="summary-grand"><span>Grand total</span><strong>{{money(total)}}</strong></div><div><span>Paid now</span><strong>{{money(form.paid_amount)}}</strong></div><div class="summary-due"><span>Balance due</span><strong>{{money(due)}}</strong></div></div><div v-if="invalidStock" class="inline-warning">Reduce the highlighted quantity before saving.</div><button class="save-transaction with-icon" :disabled="!canSave"><AppIcon :name="isSale?'sale':'purchase'"/>{{saving?'Saving…':`Save ${isSale?'sale':'purchase'}`}}</button><p class="save-note">Stock and balances update immediately after saving.</p></section></div>
</form>
</template>
