<script setup>
import {computed,onMounted,ref} from 'vue';import {useRouter} from 'vue-router';import api from '../services/api';
const props=defineProps({type:String}),router=useRouter(),products=ref([]),parties=ref([]),error=ref(''),saving=ref(false),isSale=computed(()=>props.type==='sales');
const form=ref({purchase_date:new Date().toISOString().slice(0,10),sale_date:new Date().toISOString().slice(0,10),supplier_id:'',customer_id:'',payment_method:'cash',discount:0,additional_cost:0,tax:0,paid_amount:0,items:[]});
onMounted(async()=>{products.value=(await api.get('/products',{params:{active:1,per_page:100}})).data.data.data;parties.value=(await api.get(isSale.value?'/customers':'/suppliers',{params:{per_page:100}})).data.data.data;add()});
function add(){form.value.items.push({product_id:'',quantity:1,unit_price:0,discount:0})}function product(i){return products.value.find(p=>p.id==i.product_id)}function choose(i){i.unit_price=Number(isSale.value?product(i)?.sale_price:product(i)?.purchase_price)||0}
const subtotal=computed(()=>form.value.items.reduce((s,i)=>s+Number(i.quantity)*Number(i.unit_price)-Number(i.discount||0),0)),total=computed(()=>subtotal.value-Number(form.value.discount||0)+Number(isSale.value?form.value.tax:form.value.additional_cost||0)),due=computed(()=>Math.max(0,total.value-Number(form.value.paid_amount||0))),invalid=computed(()=>isSale.value&&form.value.items.some(i=>Number(i.quantity)>Number(product(i)?.current_stock||0)));
async function save(){error.value='';saving.value=true;try{await api.post('/'+props.type,form.value);router.push('/'+props.type)}catch(e){error.value=Object.values(e.response?.data?.errors||{}).flat().join(' ')||e.response?.data?.message||'Unable to save.'}finally{saving.value=false}}
</script>
<template><div class="page-head"><h1>New {{isSale?'sale':'purchase'}}</h1><RouterLink class="btn secondary" :to="`/${type}`">Back</RouterLink></div><form @submit.prevent="save"><div v-if="error" class="error">{{error}}</div><div class="panel form-grid"><div class="field"><label>Date</label><input v-model="form[isSale?'sale_date':'purchase_date']" type="date" required></div><div class="field"><label>{{isSale?'Customer':'Supplier'}}</label><select v-model="form[isSale?'customer_id':'supplier_id']" required><option value="">Select…</option><option v-for="p in parties" :value="p.id">{{p.name}}</option></select></div><div class="field"><label>Payment method</label><select v-model="form.payment_method"><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="other">Other</option></select></div></div><div class="panel" style="margin-top:16px;overflow:auto"><table><tr><th>Product</th><th v-if="isSale">Available</th><th>Quantity</th><th>Price</th><th>Discount</th><th></th></tr><tr v-for="(i,n) in form.items"><td><select v-model="i.product_id" @change="choose(i)" required><option value="">Select product…</option><option v-for="p in products" :value="p.id">{{p.name}} ({{p.sku}})</option></select></td><td v-if="isSale">{{product(i)?.current_stock||0}}</td><td><input v-model.number="i.quantity" type="number" min=".001" step=".001" required></td><td><input v-model.number="i.unit_price" type="number" min="0" step=".01" required></td><td><input v-model.number="i.discount" type="number" min="0" step=".01"></td><td><button type="button" class="secondary" @click="form.items.splice(n,1)">Remove</button></td></tr></table><button type="button" class="secondary" style="margin-top:12px" @click="add">Add product</button></div><div class="panel form-grid" style="margin-top:16px"><div class="field"><label>Discount</label><input v-model.number="form.discount" type="number" min="0" step=".01"></div><div class="field"><label>{{isSale?'Tax':'Additional cost'}}</label><input v-model.number="form[isSale?'tax':'additional_cost']" type="number" min="0" step=".01"></div><div class="field"><label>Paid</label><input v-model.number="form.paid_amount" type="number" min="0" :max="total" step=".01"></div><div class="totals"><div><span>Subtotal</span><b>{{subtotal.toFixed(2)}}</b></div><div><span>Total</span><b>{{total.toFixed(2)}}</b></div><div><span>Due</span><b>{{due.toFixed(2)}}</b></div></div></div><div v-if="invalid" class="error">One or more items exceed available stock.</div><button style="margin-top:16px" :disabled="saving||invalid||!form.items.length">{{saving?'Saving…':'Save transaction'}}</button></form></template>
