<script setup>
import {computed,onMounted,ref} from 'vue';import api from '../services/api';import AppIcon from '../components/common/AppIcon.vue';
const users=ref([]),roles=ref([]),companies=ref([]),loading=ref(true),saving=ref(false),showForm=ref(false),editing=ref(null),search=ref(''),error=ref(''),notice=ref('');
const page=ref(1),pagination=ref({current_page:1,last_page:1,total:0,from:0,to:0,per_page:15});
const form=ref({});
const selectedRole=computed(()=>roles.value.find(role=>role.name===form.value.role));
function defaults(){form.value={name:'',email:'',password:'',password_confirmation:'',role:'Operator',company_ids:companies.value.map(x=>x.id),is_active:true}}
async function load(){loading.value=true;try{const result=(await api.get('/users',{params:{search:search.value,page:page.value}})).data.data;pagination.value={current_page:result.current_page,last_page:result.last_page,total:result.total,from:result.from||0,to:result.to||0,per_page:result.per_page};users.value=result.data.map((user,index)=>({...user,serial:(result.current_page-1)*result.per_page+index+1}))}catch(e){error.value=e.response?.data?.message||'Unable to load users.'}finally{loading.value=false}}
async function loadRoles(){roles.value=(await api.get('/users/roles')).data.data}
async function loadCompanies(){companies.value=(await api.get('/companies')).data.data}
function create(){editing.value=null;defaults();showForm.value=true;error.value=''}
function edit(user){editing.value=user.id;form.value={name:user.name,email:user.email,password:'',password_confirmation:'',role:user.roles?.[0]?.name||'Operator',company_ids:user.companies?.map(x=>x.id)||[],is_active:user.is_active};showForm.value=true;error.value=''}
async function save(){saving.value=true;error.value='';notice.value='';try{const payload={...form.value};if(editing.value&&!payload.password){delete payload.password;delete payload.password_confirmation}if(editing.value)await api.put('/users/'+editing.value,payload);else await api.post('/users',payload);showForm.value=false;notice.value=editing.value?'User updated successfully.':'User created successfully.';await load();setTimeout(()=>notice.value='',4000)}catch(e){error.value=Object.values(e.response?.data?.errors||{}).flat().join(' ')||e.response?.data?.message||'Unable to save user.'}finally{saving.value=false}}
function go(target){if(target<1||target>pagination.value.last_page)return;page.value=target;load()}
let timer;function searched(){clearTimeout(timer);page.value=1;timer=setTimeout(load,300)}
onMounted(async()=>{await Promise.all([load(),loadRoles(),loadCompanies()]);defaults()});
</script>
<template><div class="page-head"><div><span class="eyebrow">Security & access</span><h1>User administration</h1><p class="page-subtitle">Create users, assign roles, reset passwords, and control account access.</p></div><button class="with-icon" @click="create"><AppIcon name="plus"/>Create user</button></div>
<div v-if="notice" class="success-message">{{notice}}</div><div v-if="error&&!showForm" class="error">{{error}}</div>
<div class="user-admin-grid" :class="{editing:showForm}"><section class="panel list-panel"><div class="user-list-head"><div class="toolbar search-box"><AppIcon name="search"/><input v-model="search" placeholder="Search users…" @input="searched"></div><span>{{pagination.total}} user{{pagination.total===1?'':'s'}}</span></div><div v-if="loading" class="table-loading">Loading users…</div><table><thead><tr><th>S. No.</th><th>User</th><th>Role</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody><tr v-for="user in users" :key="user.id"><td>{{user.serial}}</td><td><div class="user-cell"><span>{{user.name.slice(0,1).toUpperCase()}}</span><div><strong>{{user.name}}</strong><small>{{user.email}}</small></div></div></td><td><span class="role-badge">{{user.roles?.[0]?.name||'No role'}}</span></td><td><span class="status" :class="user.is_active?'success':'neutral'">{{user.is_active?'Active':'Inactive'}}</span></td><td>{{new Date(user.created_at).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}}</td><td><button class="icon-only secondary" title="Edit user" @click="edit(user)"><AppIcon name="edit"/></button></td></tr><tr v-if="!loading&&!users.length"><td colspan="6"><div class="empty-state"><strong>No users found</strong><span>Create a user or change your search.</span></div></td></tr></tbody></table><div class="pagination" v-if="pagination.last_page>1"><span>Showing {{pagination.from}}–{{pagination.to}} of {{pagination.total}}</span><div><button class="secondary" :disabled="page===1" @click="go(page-1)">Previous</button><span>Page {{page}} of {{pagination.last_page}}</span><button class="secondary" :disabled="page===pagination.last_page" @click="go(page+1)">Next</button></div></div></section>
<aside v-if="showForm" class="panel user-form-panel"><div class="panel-head"><div><h2>{{editing?'Edit user':'Create user'}}</h2><p>{{editing?'Update access and account details.':'Add a user to the business workspace.'}}</p></div><button class="icon-only secondary" @click="showForm=false"><AppIcon name="close"/></button></div><form @submit.prevent="save"><div v-if="error" class="error">{{error}}</div><div class="field"><label>Full name</label><input v-model.trim="form.name" required></div><div class="field"><label>Email address</label><input v-model.trim="form.email" type="email" required></div><div class="field"><label>Role</label><select v-model="form.role" required><option v-for="role in roles" :value="role.name">{{role.name}}</option></select></div><div class="field"><label>Company access</label><div class="company-checks"><label v-for="company in companies" :key="company.id"><input v-model="form.company_ids" type="checkbox" :value="company.id">{{company.name}}</label></div></div><div v-if="selectedRole" class="permission-preview"><strong>{{selectedRole.name}} permissions</strong><div><span v-for="permission in selectedRole.permissions" :key="permission.id">{{permission.name.replace('.',' · ')}}</span></div></div><div class="field"><label>{{editing?'New password (optional)':'Password'}}</label><input v-model="form.password" type="password" :required="!editing" minlength="8" autocomplete="new-password"><small>At least 8 characters with letters and numbers.</small></div><div class="field"><label>Confirm password</label><input v-model="form.password_confirmation" type="password" :required="!editing||!!form.password" autocomplete="new-password"></div><label class="switch-row"><div><strong>Active account</strong><span>Inactive users cannot sign in.</span></div><input v-model="form.is_active" type="checkbox"><i></i></label><div class="form-actions"><button class="with-icon" :disabled="saving"><AppIcon name="customer"/>{{saving?'Saving…':editing?'Update user':'Create user'}}</button><button type="button" class="secondary" @click="showForm=false">Cancel</button></div></form></aside></div></template>
